//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Abms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Abms() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Abms", typeof(Abms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string AlertasVM_Activo_Display {
            get {
                return ResourceManager.GetString("AlertasVM_Activo_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información a mostrar.
        /// </summary>
        public static string AlertasVM_CamposSeleccionados_Display {
            get {
                return ResourceManager.GetString("AlertasVM_CamposSeleccionados_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condiciones Seleccionadas.
        /// </summary>
        public static string AlertasVM_CondicionesSeleccionadas_Display {
            get {
                return ResourceManager.GetString("AlertasVM_CondicionesSeleccionadas_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string AlertasVM_Descripcion_Display {
            get {
                return ResourceManager.GetString("AlertasVM_Descripcion_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio ingresar una Descripción.
        /// </summary>
        public static string AlertasVM_Descripcion_Required {
            get {
                return ResourceManager.GetString("AlertasVM_Descripcion_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Descripción debe tener entre 10 y 200 caracteres.
        /// </summary>
        public static string AlertasVM_Descripcion_StringLength {
            get {
                return ResourceManager.GetString("AlertasVM_Descripcion_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destinatarios.
        /// </summary>
        public static string AlertasVM_Destinatarios_Display {
            get {
                return ResourceManager.GetString("AlertasVM_Destinatarios_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos un destinatario.
        /// </summary>
        public static string AlertasVM_Destinatarios_Required {
            get {
                return ResourceManager.GetString("AlertasVM_Destinatarios_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir.
        /// </summary>
        public static string AlertasVM_DiasSeleccionados_Display {
            get {
                return ResourceManager.GetString("AlertasVM_DiasSeleccionados_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bajo la acción.
        /// </summary>
        public static string AlertasVM_TriggerSeleccionado_Display {
            get {
                return ResourceManager.GetString("AlertasVM_TriggerSeleccionado_Display", resourceCulture);
            }
        }
    }
}
