//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string btnLoginLabel {
            get {
                return ResourceManager.GetString("btnLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Contraseña.
        /// </summary>
        public static string btnRecuperarClaveLabel {
            get {
                return ResourceManager.GetString("btnRecuperarClaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string btnRegistrarLabel {
            get {
                return ResourceManager.GetString("btnRegistrarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer.
        /// </summary>
        public static string btnRestablecerClave {
            get {
                return ResourceManager.GetString("btnRestablecerClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código no válido..
        /// </summary>
        public static string errCodigoNoValido {
            get {
                return ResourceManager.GetString("errCodigoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de inicio de sesión no válido..
        /// </summary>
        public static string errInicioSesionNoValido {
            get {
                return ResourceManager.GetString("errInicioSesionNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aquí.
        /// </summary>
        public static string lblAqui {
            get {
                return ResourceManager.GetString("lblAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compruebe el correo electrónico para restablecer la contraseña..
        /// </summary>
        public static string lblCompruebeCorreoOlvidarClave {
            get {
                return ResourceManager.GetString("lblCompruebeCorreoOlvidarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por confirmar su correo electrónico..
        /// </summary>
        public static string lblConfirmEmailSuccessMessage {
            get {
                return ResourceManager.GetString("lblConfirmEmailSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cree una cuenta nueva..
        /// </summary>
        public static string lblCreerCuentaNueva {
            get {
                return ResourceManager.GetString("lblCreerCuentaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga clic aquí para iniciar sesión.
        /// </summary>
        public static string lblHagaClickAquiParaIniciarSesion {
            get {
                return ResourceManager.GetString("lblHagaClickAquiParaIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especifique su correo electrónico..
        /// </summary>
        public static string lblIngreseEmail {
            get {
                return ResourceManager.GetString("lblIngreseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpos Performance.
        /// </summary>
        public static string lblLogoLabelCheckposPerformance {
            get {
                return ResourceManager.GetString("lblLogoLabelCheckposPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se restableció la contraseña..
        /// </summary>
        public static string lblMensajeSeReestablecioLaClave {
            get {
                return ResourceManager.GetString("lblMensajeSeReestablecioLaClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidé mi contraseña / Primer Ingreso.
        /// </summary>
        public static string lblOlvideMiClave {
            get {
                return ResourceManager.GetString("lblOlvideMiClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ha solicitado el restablecimiento de contraseña para la aplicacion CheckPOS.&lt;br&gt;Para restablecer la contraseña, haga clic.
        /// </summary>
        public static string lblReestablecerPasswordBody1 {
            get {
                return ResourceManager.GetString("lblReestablecerPasswordBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si usted no solicito el restablecimiento de contraseña ignore este mensaje o bien pongase en contacto con soporte@checkpos.com.
        /// </summary>
        public static string lblReestablecerPasswordBody2 {
            get {
                return ResourceManager.GetString("lblReestablecerPasswordBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este mensaje fue originado automáticamente. Por favor no responder al mismo..
        /// </summary>
        public static string lblReestablecerPasswordBody3 {
            get {
                return ResourceManager.GetString("lblReestablecerPasswordBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer contraseña.
        /// </summary>
        public static string lblReestablecerPasswordSubject {
            get {
                return ResourceManager.GetString("lblReestablecerPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de contraseña olvidada.
        /// </summary>
        public static string lblTituloConfirmacionOlvidarClave {
            get {
                return ResourceManager.GetString("lblTituloConfirmacionOlvidarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de restablecimiento de contraseña.
        /// </summary>
        public static string lblTituloConfirmarClaveReset {
            get {
                return ResourceManager.GetString("lblTituloConfirmarClaveReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar correo electrónico.
        /// </summary>
        public static string lblTituloConfirmEmail {
            get {
                return ResourceManager.GetString("lblTituloConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidó la contraseña?.
        /// </summary>
        public static string lblTituloForgotPassword {
            get {
                return ResourceManager.GetString("lblTituloForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string lblTituloLogin {
            get {
                return ResourceManager.GetString("lblTituloLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Usuario.
        /// </summary>
        public static string lblTituloRegistrarUsuario {
            get {
                return ResourceManager.GetString("lblTituloRegistrarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer contraseña.
        /// </summary>
        public static string lblTituloResetPassword {
            get {
                return ResourceManager.GetString("lblTituloResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string placeholderClave {
            get {
                return ResourceManager.GetString("placeholderClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string placeholderConfirmarClave {
            get {
                return ResourceManager.GetString("placeholderConfirmarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string placeholderEmail {
            get {
                return ResourceManager.GetString("placeholderEmail", resourceCulture);
            }
        }
    }
}
