//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Alertas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Alertas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Alertas", typeof(Alertas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string AlertasVM_Activo_Display {
            get {
                return ResourceManager.GetString("AlertasVM_Activo_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información a mostrar.
        /// </summary>
        public static string AlertasVM_CamposSeleccionados_Display {
            get {
                return ResourceManager.GetString("AlertasVM_CamposSeleccionados_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones Seleccionadas.
        /// </summary>
        public static string AlertasVM_CondicionesSeleccionadas_Display {
            get {
                return ResourceManager.GetString("AlertasVM_CondicionesSeleccionadas_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string AlertasVM_Descripcion_Display {
            get {
                return ResourceManager.GetString("AlertasVM_Descripcion_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es obligatorio ingresar una Descripción.
        /// </summary>
        public static string AlertasVM_Descripcion_Required {
            get {
                return ResourceManager.GetString("AlertasVM_Descripcion_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Descripción debe tener entre 10 y 200 caracteres.
        /// </summary>
        public static string AlertasVM_Descripcion_StringLength {
            get {
                return ResourceManager.GetString("AlertasVM_Descripcion_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatarios.
        /// </summary>
        public static string AlertasVM_Destinatarios_Display {
            get {
                return ResourceManager.GetString("AlertasVM_Destinatarios_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar al menos un destinatario.
        /// </summary>
        public static string AlertasVM_Destinatarios_Required {
            get {
                return ResourceManager.GetString("AlertasVM_Destinatarios_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir.
        /// </summary>
        public static string AlertasVM_DiasSeleccionados_Display {
            get {
                return ResourceManager.GetString("AlertasVM_DiasSeleccionados_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajo la acción.
        /// </summary>
        public static string AlertasVM_TriggerSeleccionado_Display {
            get {
                return ResourceManager.GetString("AlertasVM_TriggerSeleccionado_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string btnBuscarAlertaLabel {
            get {
                return ResourceManager.GetString("btnBuscarAlertaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar y volver a la lista.
        /// </summary>
        public static string btnCancelarEditarYVolverALaLista {
            get {
                return ResourceManager.GetString("btnCancelarEditarYVolverALaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar y volver a la lista.
        /// </summary>
        public static string btnCancelarYVolverALaLista {
            get {
                return ResourceManager.GetString("btnCancelarYVolverALaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Alerta.
        /// </summary>
        public static string btnCrearAlertaLabel {
            get {
                return ResourceManager.GetString("btnCrearAlertaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btnEditarAlertaCancelar {
            get {
                return ResourceManager.GetString("btnEditarAlertaCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cambios.
        /// </summary>
        public static string btnEditarGuardarCambiosLabel {
            get {
                return ResourceManager.GetString("btnEditarGuardarCambiosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string btnEditarLabel {
            get {
                return ResourceManager.GetString("btnEditarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string btnEliminarLabel {
            get {
                return ResourceManager.GetString("btnEliminarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Alerta.
        /// </summary>
        public static string btnGuardarAlertaLabel {
            get {
                return ResourceManager.GetString("btnGuardarAlertaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string btnVerLabel {
            get {
                return ResourceManager.GetString("btnVerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver a la lista.
        /// </summary>
        public static string btnVolverALaListaLabel {
            get {
                return ResourceManager.GetString("btnVolverALaListaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde esta pantalla puede crear, modificar o eliminar Alertas de la aplicación.
        /// </summary>
        public static string lblAlertasIndexSubTitulo {
            get {
                return ResourceManager.GetString("lblAlertasIndexSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Alertas.
        /// </summary>
        public static string lblAlertasIndexTitulo2 {
            get {
                return ResourceManager.GetString("lblAlertasIndexTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscando alertas....
        /// </summary>
        public static string lblBuscandoAlertas {
            get {
                return ResourceManager.GetString("lblBuscandoAlertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distancia Maxima (metros).
        /// </summary>
        public static string lblDistanciaMaxima {
            get {
                return ResourceManager.GetString("lblDistanciaMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distancia Minima (metros).
        /// </summary>
        public static string lblDistanciaMinima {
            get {
                return ResourceManager.GetString("lblDistanciaMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea eliminar la alerta?.
        /// </summary>
        public static string lblSeguroDeseaEliminarLaAlerta {
            get {
                return ResourceManager.GetString("lblSeguroDeseaEliminarLaAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string lblTableColActivo {
            get {
                return ResourceManager.GetString("lblTableColActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatarios.
        /// </summary>
        public static string lblTableColDestinatarios {
            get {
                return ResourceManager.GetString("lblTableColDestinatarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string lblTableColNombre {
            get {
                return ResourceManager.GetString("lblTableColNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Reporte.
        /// </summary>
        public static string lblTableColTipoReporte {
            get {
                return ResourceManager.GetString("lblTableColTipoReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertas.
        /// </summary>
        public static string lblTituloAlertasIndex {
            get {
                return ResourceManager.GetString("lblTituloAlertasIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Alerta.
        /// </summary>
        public static string lblTituloCrearAlerta {
            get {
                return ResourceManager.GetString("lblTituloCrearAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Alerta.
        /// </summary>
        public static string lblTituloEditarAlerta {
            get {
                return ResourceManager.GetString("lblTituloEditarAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Alerta.
        /// </summary>
        public static string lblTituloEliminarAlerta {
            get {
                return ResourceManager.GetString("lblTituloEliminarAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos/Ninguno.
        /// </summary>
        public static string lblTodoNinguno {
            get {
                return ResourceManager.GetString("lblTodoNinguno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Alerta.
        /// </summary>
        public static string lblVerAlertasTitulo {
            get {
                return ResourceManager.GetString("lblVerAlertasTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string placeholderSearch {
            get {
                return ResourceManager.GetString("placeholderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta.
        /// </summary>
        public static string placeholderSearchTextAlertas {
            get {
                return ResourceManager.GetString("placeholderSearchTextAlertas", resourceCulture);
            }
        }
    }
}
