//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Calendario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Calendario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Calendario", typeof(Calendario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Evento.
        /// </summary>
        public static string btnCrearEventoLabel {
            get {
                return ResourceManager.GetString("btnCrearEventoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar a Excel.
        /// </summary>
        public static string btnDescargarExcel {
            get {
                return ResourceManager.GetString("btnDescargarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar evento.
        /// </summary>
        public static string btnEditarEventoLabel {
            get {
                return ResourceManager.GetString("btnEditarEventoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string FechaDesde {
            get {
                return ResourceManager.GetString("FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string FechaHasta {
            get {
                return ResourceManager.GetString("FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede asignar y modificar eventos en el calendario para organizar las tareas de los usuarios.
        /// </summary>
        public static string lblCalendarioSubTitulo {
            get {
                return ResourceManager.GetString("lblCalendarioSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos de usuarios.
        /// </summary>
        public static string lblCalendarioTitulo2 {
            get {
                return ResourceManager.GetString("lblCalendarioTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando eventos....
        /// </summary>
        public static string lblCargandoEventos {
            get {
                return ResourceManager.GetString("lblCargandoEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando puntos de venta....
        /// </summary>
        public static string lblCargandoPdv {
            get {
                return ResourceManager.GetString("lblCargandoPdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando puntos de venta....
        /// </summary>
        public static string lblCargandoPuntosDeVenta {
            get {
                return ResourceManager.GetString("lblCargandoPuntosDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string lblCerrar {
            get {
                return ResourceManager.GetString("lblCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Evento.
        /// </summary>
        public static string lblCrearEventoTitulo {
            get {
                return ResourceManager.GetString("lblCrearEventoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Evento de Calendario.
        /// </summary>
        public static string lblCrearEventoTitulo2 {
            get {
                return ResourceManager.GetString("lblCrearEventoTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de Evento.
        /// </summary>
        public static string lblDetalleEvento {
            get {
                return ResourceManager.GetString("lblDetalleEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Evento de Calendario.
        /// </summary>
        public static string lblEditarEventoTitulo2 {
            get {
                return ResourceManager.GetString("lblEditarEventoTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string lblEventoTableColCiudad {
            get {
                return ResourceManager.GetString("lblEventoTableColCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Evento.
        /// </summary>
        public static string lblEventoTableColCodigoEvento {
            get {
                return ResourceManager.GetString("lblEventoTableColCodigoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto.
        /// </summary>
        public static string lblEventoTableColConcepto {
            get {
                return ResourceManager.GetString("lblEventoTableColConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string lblEventoTableColFecha {
            get {
                return ResourceManager.GetString("lblEventoTableColFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Evento.
        /// </summary>
        public static string lblEventoTableColIdEvento {
            get {
                return ResourceManager.GetString("lblEventoTableColIdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id punto de venta.
        /// </summary>
        public static string lblEventoTableColIdPuntoDeVenta {
            get {
                return ResourceManager.GetString("lblEventoTableColIdPuntoDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string lblEventoTableColObservaciones {
            get {
                return ResourceManager.GetString("lblEventoTableColObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta.
        /// </summary>
        public static string lblEventoTableColPuntoDeVenta {
            get {
                return ResourceManager.GetString("lblEventoTableColPuntoDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string lblEventoTableColUsuario {
            get {
                return ResourceManager.GetString("lblEventoTableColUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Evento.
        /// </summary>
        public static string lblLinkEliminarEvento {
            get {
                return ResourceManager.GetString("lblLinkEliminarEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver a vista Calendario.
        /// </summary>
        public static string lblListadoEventosCancelarYVolver {
            get {
                return ResourceManager.GetString("lblListadoEventosCancelarYVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Eventos Calendario.
        /// </summary>
        public static string lblListadoEventosTitulo {
            get {
                return ResourceManager.GetString("lblListadoEventosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Eventos.
        /// </summary>
        public static string lblListadoEventosTitulo2 {
            get {
                return ResourceManager.GetString("lblListadoEventosTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string lblLoading {
            get {
                return ResourceManager.GetString("lblLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron datos..
        /// </summary>
        public static string lblNoSeEncontraronDatos {
            get {
                return ResourceManager.GetString("lblNoSeEncontraronDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede eliminar este evento haciendo en.
        /// </summary>
        public static string lblPuedeEliminarEventoHaciendoClickEn {
            get {
                return ResourceManager.GetString("lblPuedeEliminarEventoHaciendoClickEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea eliminar este evento?.
        /// </summary>
        public static string lblSeguroDeseaEliminarEvento {
            get {
                return ResourceManager.GetString("lblSeguroDeseaEliminarEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendario.
        /// </summary>
        public static string lblTituloCalendarioIndex {
            get {
                return ResourceManager.GetString("lblTituloCalendarioIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Evento.
        /// </summary>
        public static string lblTituloEditarEvento {
            get {
                return ResourceManager.GetString("lblTituloEditarEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Evento.
        /// </summary>
        public static string linkCrearEventoLabel {
            get {
                return ResourceManager.GetString("linkCrearEventoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Planilla.
        /// </summary>
        public static string linkVerPlanillaLabel {
            get {
                return ResourceManager.GetString("linkVerPlanillaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un concepto.
        /// </summary>
        public static string placeholderDdlConcepto {
            get {
                return ResourceManager.GetString("placeholderDdlConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un punto de venta.
        /// </summary>
        public static string placeholderDdlPdv {
            get {
                return ResourceManager.GetString("placeholderDdlPdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un usuario.
        /// </summary>
        public static string placeholderDdlUsuarios {
            get {
                return ResourceManager.GetString("placeholderDdlUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un concepto.
        /// </summary>
        public static string placeholderSeleccioneConcepto {
            get {
                return ResourceManager.GetString("placeholderSeleccioneConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un punto de venta.
        /// </summary>
        public static string placeholderSeleccionePdv {
            get {
                return ResourceManager.GetString("placeholderSeleccionePdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un usuario.
        /// </summary>
        public static string placeholderSeleccioneUsuario {
            get {
                return ResourceManager.GetString("placeholderSeleccioneUsuario", resourceCulture);
            }
        }
    }
}
