//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Configuracion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuracion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Configuracion", typeof(Configuracion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Nuevo Rol.
        /// </summary>
        public static string btnCrearNuevoRolLabel {
            get {
                return ResourceManager.GetString("btnCrearNuevoRolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cambios.
        /// </summary>
        public static string btnCrearRolLabel {
            get {
                return ResourceManager.GetString("btnCrearRolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Cambios.
        /// </summary>
        public static string btnMarcaBlancaGuardarCambios {
            get {
                return ResourceManager.GetString("btnMarcaBlancaGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar Reporting.
        /// </summary>
        public static string btnUsuariosActivarReporting {
            get {
                return ResourceManager.GetString("btnUsuariosActivarReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cambio se realizó correctamente.
        /// </summary>
        public static string cambioRealizadoConExito {
            get {
                return ResourceManager.GetString("cambioRealizadoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar asignar los permisos.
        /// </summary>
        public static string confAsignarPermisosError {
            get {
                return ResourceManager.GetString("confAsignarPermisosError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdObligatorio.
        /// </summary>
        public static string confFiltroIdRequerido {
            get {
                return ResourceManager.GetString("confFiltroIdRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de Filtro es obligatorio.
        /// </summary>
        public static string confFiltroLeyendaRequerida {
            get {
                return ResourceManager.GetString("confFiltroLeyendaRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de 50 caracteres.
        /// </summary>
        public static string confFiltroLeyendaTooLong {
            get {
                return ResourceManager.GetString("confFiltroLeyendaTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        public static string confFiltroModuloLabel {
            get {
                return ResourceManager.GetString("confFiltroModuloLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron filtros.
        /// </summary>
        public static string confFiltroSinFiltros {
            get {
                return ResourceManager.GetString("confFiltroSinFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca Blanca.
        /// </summary>
        public static string confMenuMarcaBlanca {
            get {
                return ResourceManager.GetString("confMenuMarcaBlanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Filtros.
        /// </summary>
        public static string confMenuNombreFiltros {
            get {
                return ResourceManager.GetString("confMenuNombreFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetos.
        /// </summary>
        public static string confMenuObjetos {
            get {
                return ResourceManager.GetString("confMenuObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string confMenuRoles {
            get {
                return ResourceManager.GetString("confMenuRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string confMenuUsuarios {
            get {
                return ResourceManager.GetString("confMenuUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibilidad de Objetos.
        /// </summary>
        public static string confMenuVisibilidadFamilias {
            get {
                return ResourceManager.GetString("confMenuVisibilidadFamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibilidad Filtros.
        /// </summary>
        public static string confMenuVisibilidadFiltros {
            get {
                return ResourceManager.GetString("confMenuVisibilidadFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibilidad entre usuarios.
        /// </summary>
        public static string confMenuVisibilidadUsuarios {
            get {
                return ResourceManager.GetString("confMenuVisibilidadUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Obligatorio.
        /// </summary>
        public static string confObjetoIdRequerido {
            get {
                return ResourceManager.GetString("confObjetoIdRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de Objeto es obligatorio.
        /// </summary>
        public static string confObjetoLeyendaRequerida {
            get {
                return ResourceManager.GetString("confObjetoLeyendaRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de 50 caracteres.
        /// </summary>
        public static string confObjetoLeyendaTooLong {
            get {
                return ResourceManager.GetString("confObjetoLeyendaTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string confRolAsignarPermisos {
            get {
                return ResourceManager.GetString("confRolAsignarPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Rol fue creado exitosamente.
        /// </summary>
        public static string confRolCreadoExitosamente {
            get {
                return ResourceManager.GetString("confRolCreadoExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Rol ya existe.
        /// </summary>
        public static string confRolDuplicado {
            get {
                return ResourceManager.GetString("confRolDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear el Rol.
        /// </summary>
        public static string confRolError {
            get {
                return ResourceManager.GetString("confRolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string confRolLabel {
            get {
                return ResourceManager.GetString("confRolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de 50 caracteres.
        /// </summary>
        public static string confRolNameMaxLengthError {
            get {
                return ResourceManager.GetString("confRolNameMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del Rol no puede ser vacío.
        /// </summary>
        public static string confRolNameRequiredError {
            get {
                return ResourceManager.GetString("confRolNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido no puede quedar vacio.
        /// </summary>
        public static string confUsuarioApellidoRequired {
            get {
                return ResourceManager.GetString("confUsuarioApellidoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Roles al Usuario.
        /// </summary>
        public static string confUsuarioAsignarRolLabel {
            get {
                return ResourceManager.GetString("confUsuarioAsignarRolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string confUsuarioConfirmPassword {
            get {
                return ResourceManager.GetString("confUsuarioConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Email no puede quedar vacio.
        /// </summary>
        public static string confUsuarioEmailNotNull {
            get {
                return ResourceManager.GetString("confUsuarioEmailNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre no puede quedar vacio.
        /// </summary>
        public static string confUsuarioNombreRequired {
            get {
                return ResourceManager.GetString("confUsuarioNombreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos Nombre y Apellido no pueden quedar vacios.
        /// </summary>
        public static string confUsuarioNotNull {
            get {
                return ResourceManager.GetString("confUsuarioNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener al menos 6 caracteres.
        /// </summary>
        public static string confUsuarioPasswordLength {
            get {
                return ResourceManager.GetString("confUsuarioPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar una contraseña.
        /// </summary>
        public static string confUsuarioPasswordNotNull {
            get {
                return ResourceManager.GetString("confUsuarioPasswordNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar permisos al Rol.
        /// </summary>
        public static string crearNuevoRolAsignarPermisosTitle {
            get {
                return ResourceManager.GetString("crearNuevoRolAsignarPermisosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nuevo Rol.
        /// </summary>
        public static string crearNuevoRolButton {
            get {
                return ResourceManager.GetString("crearNuevoRolButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nuevo Rol.
        /// </summary>
        public static string crearNuevoRolModalTitulo {
            get {
                return ResourceManager.GetString("crearNuevoRolModalTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nuevo usuario.
        /// </summary>
        public static string crearNuevoUsuarioButton {
            get {
                return ResourceManager.GetString("crearNuevoUsuarioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string crearNuevoUsuarioConfirmPassword {
            get {
                return ResourceManager.GetString("crearNuevoUsuarioConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string crearNuevoUsuarioEmail {
            get {
                return ResourceManager.GetString("crearNuevoUsuarioEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string crearNuevoUsuarioFirstName {
            get {
                return ResourceManager.GetString("crearNuevoUsuarioFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string crearNuevoUsuarioLastName {
            get {
                return ResourceManager.GetString("crearNuevoUsuarioLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nuevo usuario.
        /// </summary>
        public static string crearNuevoUsuarioModalTitulo {
            get {
                return ResourceManager.GetString("crearNuevoUsuarioModalTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string crearNuevoUsuarioPassword {
            get {
                return ResourceManager.GetString("crearNuevoUsuarioPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al asignar el usuario de performance con el creado en reporting.
        /// </summary>
        public static string errAsignarUsuarioPerformanceReporting {
            get {
                return ResourceManager.GetString("errAsignarUsuarioPerformanceReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Inesperado al intentar cargar el formulario para editar el nombre del filtro.
        /// </summary>
        public static string errCargarFormularioNombreFiltro {
            get {
                return ResourceManager.GetString("errCargarFormularioNombreFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar guardar los datos del rol..
        /// </summary>
        public static string errDatosRolGuardar {
            get {
                return ResourceManager.GetString("errDatosRolGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar guardarlos datos de usuario..
        /// </summary>
        public static string errEditarUsuarioGuardar {
            get {
                return ResourceManager.GetString("errEditarUsuarioGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe tener máximo 50 caracteres.
        /// </summary>
        public static string errFamiliaNombreAsignadoLength {
            get {
                return ResourceManager.GetString("errFamiliaNombreAsignadoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los formatos de imagen soportados son gif, jpg, png.
        /// </summary>
        public static string errFormatoImagen {
            get {
                return ResourceManager.GetString("errFormatoImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar guardar los datos del rol..
        /// </summary>
        public static string errGuardarDatosNuevoRol {
            get {
                return ResourceManager.GetString("errGuardarDatosNuevoRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo realizar la modificación, el nombre de objeto no puede superar los 100 caracteres.
        /// </summary>
        public static string errGuardarNombreObjeto {
            get {
                return ResourceManager.GetString("errGuardarNombreObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de la imagen es incorrecto.
        /// </summary>
        public static string errImagenFormato {
            get {
                return ResourceManager.GetString("errImagenFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imagen no puede superarlos 500kb.
        /// </summary>
        public static string errImagenSize {
            get {
                return ResourceManager.GetString("errImagenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Imagen no puede pesar mas de 500kb.
        /// </summary>
        public static string errImagenSize500kb {
            get {
                return ResourceManager.GetString("errImagenSize500kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al intentar realizar la modificación. Si persiste contacte a soporte. Disculpe las molestias..
        /// </summary>
        public static string errInesperadoModificacion {
            get {
                return ResourceManager.GetString("errInesperadoModificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al intentar crear el usuario en reporting.
        /// </summary>
        public static string errIntentarCrearUsuario {
            get {
                return ResourceManager.GetString("errIntentarCrearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Formato de la imagen elegida es incorrecto..
        /// </summary>
        public static string errMarcaBlancaImagenFormato {
            get {
                return ResourceManager.GetString("errMarcaBlancaImagenFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño máximo de la foto debe ser de 500kb..
        /// </summary>
        public static string errMarcaBlancaImagenSize {
            get {
                return ResourceManager.GetString("errMarcaBlancaImagenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Inesperado al intentar cargar el formulario para editar el nombre del Objeto.
        /// </summary>
        public static string errObjetosCargarFormularioNombre {
            get {
                return ResourceManager.GetString("errObjetosCargarFormularioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño de la imagen no puede exceder los 300kb.
        /// </summary>
        public static string errorSizeImagenMarcaBlanca {
            get {
                return ResourceManager.GetString("errorSizeImagenMarcaBlanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño de la imagen no puede exceder los 100kb.
        /// </summary>
        public static string errorSizeLogoMarcaBlanca {
            get {
                return ResourceManager.GetString("errorSizeLogoMarcaBlanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imagen no tiene un formato válido. Los posibles formatos son: jpg, png, gif.
        /// </summary>
        public static string errorTipoImagenMarcaBlanca {
            get {
                return ResourceManager.GetString("errorTipoImagenMarcaBlanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar/Desactivar el uso de Marca Blanca.
        /// </summary>
        public static string flgMarcaBlancaLabel {
            get {
                return ResourceManager.GetString("flgMarcaBlancaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen Footer.
        /// </summary>
        public static string footerMarcaBlancaLabel {
            get {
                return ResourceManager.GetString("footerMarcaBlancaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen de Fondo.
        /// </summary>
        public static string imgMarcaBlancaLabel {
            get {
                return ResourceManager.GetString("imgMarcaBlancaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es obligatorio seleccionar una imagen.
        /// </summary>
        public static string imgMarcaBlancaRequired {
            get {
                return ResourceManager.GetString("imgMarcaBlancaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen cargada actualmente.
        /// </summary>
        public static string imgPreviewMarcaBlancaLabel {
            get {
                return ResourceManager.GetString("imgPreviewMarcaBlancaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Ad-Hoc:.
        /// </summary>
        public static string lblAdHoc {
            get {
                return ResourceManager.GetString("lblAdHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        public static string lblAdministracion {
            get {
                return ResourceManager.GetString("lblAdministracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Filtros.
        /// </summary>
        public static string lblAsignacionFiltros {
            get {
                return ResourceManager.GetString("lblAsignacionFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede administrar que Filtros son visibles para el usuario.
        /// </summary>
        public static string lblAsignacionFiltrosSubTitulo {
            get {
                return ResourceManager.GetString("lblAsignacionFiltrosSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Filtros.
        /// </summary>
        public static string lblAsignacionFiltrosTitulo2 {
            get {
                return ResourceManager.GetString("lblAsignacionFiltrosTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Objetos.
        /// </summary>
        public static string lblAsignacionObjetos {
            get {
                return ResourceManager.GetString("lblAsignacionObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administre que objetos se asignan al cliente.
        /// </summary>
        public static string lblAsignacionObjetosSubTitulo {
            get {
                return ResourceManager.GetString("lblAsignacionObjetosSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Objetos.
        /// </summary>
        public static string lblAsignacionObjetosTitulo2 {
            get {
                return ResourceManager.GetString("lblAsignacionObjetosTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Objetos.
        /// </summary>
        public static string lblAsignarObjetosTitulo {
            get {
                return ResourceManager.GetString("lblAsignarObjetosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string lblCancelar {
            get {
                return ResourceManager.GetString("lblCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando filtros....
        /// </summary>
        public static string lblCargandoFiltros {
            get {
                return ResourceManager.GetString("lblCargandoFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string lblConfiguracionIndexTitulo {
            get {
                return ResourceManager.GetString("lblConfiguracionIndexTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede modificar la leyenda y visibilidad de los filtros para cada módulo de la aplicación.
        /// </summary>
        public static string lblConfigurarFiltrosSubTitulo {
            get {
                return ResourceManager.GetString("lblConfigurarFiltrosSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Filtros.
        /// </summary>
        public static string lblConfigurarFiltrosTitulo {
            get {
                return ResourceManager.GetString("lblConfigurarFiltrosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de Filtros.
        /// </summary>
        public static string lblConfigurarFiltrosTitulo2 {
            get {
                return ResourceManager.GetString("lblConfigurarFiltrosTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede modificar la leyenda y visibilidad de los objetos de tableros de la aplicación.
        /// </summary>
        public static string lblConfigurarObjetosSubTitulo {
            get {
                return ResourceManager.GetString("lblConfigurarObjetosSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Objetos.
        /// </summary>
        public static string lblConfigurarObjetosTitulo {
            get {
                return ResourceManager.GetString("lblConfigurarObjetosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Objetos.
        /// </summary>
        public static string lblConfigurarObjetosTitulo2 {
            get {
                return ResourceManager.GetString("lblConfigurarObjetosTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string lblConfirmar {
            get {
                return ResourceManager.GetString("lblConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Rol.
        /// </summary>
        public static string lblCrearRolTitulo {
            get {
                return ResourceManager.GetString("lblCrearRolTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Rol.
        /// </summary>
        public static string lblCrearRolTitulo2 {
            get {
                return ResourceManager.GetString("lblCrearRolTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos del rol se guardaron exitosamente.
        /// </summary>
        public static string lblDatosGuardaronExitosamente {
            get {
                return ResourceManager.GetString("lblDatosGuardaronExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos del rol se guardaron exitosamente.
        /// </summary>
        public static string lblDatosRolGuardadosExito {
            get {
                return ResourceManager.GetString("lblDatosRolGuardadosExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Nombre de Filtro.
        /// </summary>
        public static string lblEditarNombreFiltro {
            get {
                return ResourceManager.GetString("lblEditarNombreFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Cambios.
        /// </summary>
        public static string lblEditarRolGuardarCambios {
            get {
                return ResourceManager.GetString("lblEditarRolGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permiso.
        /// </summary>
        public static string lblEditarRolPermiso {
            get {
                return ResourceManager.GetString("lblEditarRolPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisos.
        /// </summary>
        public static string lblEditarRolPermisos {
            get {
                return ResourceManager.GetString("lblEditarRolPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionado.
        /// </summary>
        public static string lblEditarRolSeleccionado {
            get {
                return ResourceManager.GetString("lblEditarRolSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Rol.
        /// </summary>
        public static string lblEditarRolTitulo {
            get {
                return ResourceManager.GetString("lblEditarRolTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Rol.
        /// </summary>
        public static string lblEditarRolTitulo2 {
            get {
                return ResourceManager.GetString("lblEditarRolTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es CheckPos.
        /// </summary>
        public static string lblEditarUsuarioEsCheckpos {
            get {
                return ResourceManager.GetString("lblEditarUsuarioEsCheckpos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos de usuario se guardaron exitosamente.
        /// </summary>
        public static string lblEditarUsuarioGuardadoExitoso {
            get {
                return ResourceManager.GetString("lblEditarUsuarioGuardadoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Cambios.
        /// </summary>
        public static string lblEditarUsuarioGuardarCambios {
            get {
                return ResourceManager.GetString("lblEditarUsuarioGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede modificar calendario.
        /// </summary>
        public static string lblEditarUsuarioModificarCalendario {
            get {
                return ResourceManager.GetString("lblEditarUsuarioModificarCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Usuario.
        /// </summary>
        public static string lblEditarUsuarioTitulo {
            get {
                return ResourceManager.GetString("lblEditarUsuarioTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Usuario.
        /// </summary>
        public static string lblEditarUsuarioTitulo2 {
            get {
                return ResourceManager.GetString("lblEditarUsuarioTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string lblEmpresa {
            get {
                return ResourceManager.GetString("lblEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo realizar la modificación, el nombre de filtro no puede superar los 50 caracteres.
        /// </summary>
        public static string lblErrNombreFiltro {
            get {
                return ResourceManager.GetString("lblErrNombreFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string lblFiltros {
            get {
                return ResourceManager.GetString("lblFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando nuevo nombre de objeto....
        /// </summary>
        public static string lblGuardandoNombreObjeto {
            get {
                return ResourceManager.GetString("lblGuardandoNombreObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Cambios.
        /// </summary>
        public static string lblGuardarCambios {
            get {
                return ResourceManager.GetString("lblGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando nuevo nombre de filtro....
        /// </summary>
        public static string lblGuardarNombreDeFiltro {
            get {
                return ResourceManager.GetString("lblGuardarNombreDeFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca Blanca.
        /// </summary>
        public static string lblMarcaBlanca {
            get {
                return ResourceManager.GetString("lblMarcaBlanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: 500kb. Recomendado: 1366x768.
        /// </summary>
        public static string lblMarcaBlancaResolucionRecomendada {
            get {
                return ResourceManager.GetString("lblMarcaBlancaResolucionRecomendada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: 500kb. Recomendado: 140x40.
        /// </summary>
        public static string lblMarcaBlancaResolucionRecomendada2 {
            get {
                return ResourceManager.GetString("lblMarcaBlancaResolucionRecomendada2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max: 500kb. Recomendado: 1366x100.
        /// </summary>
        public static string lblMarcaBlancaResolucionRecomendada3 {
            get {
                return ResourceManager.GetString("lblMarcaBlancaResolucionRecomendada3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde esta pantalla puede adaptar el estilo del sitio para que corresponda con su marca..
        /// </summary>
        public static string lblMarcaBlancaSubTitulo {
            get {
                return ResourceManager.GetString("lblMarcaBlancaSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca Blanca.
        /// </summary>
        public static string lblMarcaBlancaTitulo {
            get {
                return ResourceManager.GetString("lblMarcaBlancaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca Blanca.
        /// </summary>
        public static string lblMarcaBlancaTitulo2 {
            get {
                return ResourceManager.GetString("lblMarcaBlancaTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de filtro que ingrese es el que se va a ver en el filtro lateral de Reporting..
        /// </summary>
        public static string lblNombreFiltroAviso {
            get {
                return ResourceManager.GetString("lblNombreFiltroAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre por Defecto:.
        /// </summary>
        public static string lblNombrePorDefecto {
            get {
                return ResourceManager.GetString("lblNombrePorDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetos.
        /// </summary>
        public static string lblObjetos {
            get {
                return ResourceManager.GetString("lblObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Asignado por Usuario.
        /// </summary>
        public static string lblObjetosTablaColNombreAsignado {
            get {
                return ResourceManager.GetString("lblObjetosTablaColNombreAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre por Defecto.
        /// </summary>
        public static string lblObjetosTablaColNombreDefecto {
            get {
                return ResourceManager.GetString("lblObjetosTablaColNombreDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibilidad.
        /// </summary>
        public static string lblObjetosTablaColVisibilidad {
            get {
                return ResourceManager.GetString("lblObjetosTablaColVisibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string lblOnOffLabelNo {
            get {
                return ResourceManager.GetString("lblOnOffLabelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string lblOnOffLabelYes {
            get {
                return ResourceManager.GetString("lblOnOffLabelYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string lblPerfilApellido {
            get {
                return ResourceManager.GetString("lblPerfilApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblPerfilEmail {
            get {
                return ResourceManager.GetString("lblPerfilEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string lblPerfilIdioma {
            get {
                return ResourceManager.GetString("lblPerfilIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string lblPerfilNombre {
            get {
                return ResourceManager.GetString("lblPerfilNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string lblPerfilRol {
            get {
                return ResourceManager.GetString("lblPerfilRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string lblPerfilTelefono {
            get {
                return ResourceManager.GetString("lblPerfilTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permiso.
        /// </summary>
        public static string lblPermiso {
            get {
                return ResourceManager.GetString("lblPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisos.
        /// </summary>
        public static string lblPermisos {
            get {
                return ResourceManager.GetString("lblPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerar Usuario.
        /// </summary>
        public static string lblRegenerarUsuario {
            get {
                return ResourceManager.GetString("lblRegenerarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        public static string lblReporting {
            get {
                return ResourceManager.GetString("lblReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string lblRoles {
            get {
                return ResourceManager.GetString("lblRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de roles, puede modificar y crear nuevos roles con distintos permisos.
        /// </summary>
        public static string lblRolesSubTitulo {
            get {
                return ResourceManager.GetString("lblRolesSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string lblRolesTablaColNombre {
            get {
                return ResourceManager.GetString("lblRolesTablaColNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string lblRolesTitulo {
            get {
                return ResourceManager.GetString("lblRolesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de Roles.
        /// </summary>
        public static string lblRolesTitulo2 {
            get {
                return ResourceManager.GetString("lblRolesTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aquí.
        /// </summary>
        public static string lblRolNoEncontradoAqui {
            get {
                return ResourceManager.GetString("lblRolNoEncontradoAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede ir al listado de roles haciendo click.
        /// </summary>
        public static string lblRolNoEncontradoLink1 {
            get {
                return ResourceManager.GetString("lblRolNoEncontradoLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el rol que está buscando.
        /// </summary>
        public static string lblRolNoEncontradoMensaje {
            get {
                return ResourceManager.GetString("lblRolNoEncontradoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esto no afectará sus datos..
        /// </summary>
        public static string lblRolNoEncontradonoAfectaDatos {
            get {
                return ResourceManager.GetString("lblRolNoEncontradonoAfectaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol No Encontrado.
        /// </summary>
        public static string lblRolNoEncontradoTitulo {
            get {
                return ResourceManager.GetString("lblRolNoEncontradoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionado.
        /// </summary>
        public static string lblSeleccionado {
            get {
                return ResourceManager.GetString("lblSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignado.
        /// </summary>
        public static string lblTablaColAsignado {
            get {
                return ResourceManager.GetString("lblTablaColAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignado.
        /// </summary>
        public static string lblTablaColAsignadoAsignacionObjetos {
            get {
                return ResourceManager.GetString("lblTablaColAsignadoAsignacionObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string lblTablaColCategoriaAsignacionObjetos {
            get {
                return ResourceManager.GetString("lblTablaColCategoriaAsignacionObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string lblTablaColNombre {
            get {
                return ResourceManager.GetString("lblTablaColNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string lblTablaColNombreAsignacionObjetos {
            get {
                return ResourceManager.GetString("lblTablaColNombreAsignacionObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Asignado por Usuario.
        /// </summary>
        public static string lblTablaColNombreAsignadoPorUsuario {
            get {
                return ResourceManager.GetString("lblTablaColNombreAsignadoPorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre por Defecto.
        /// </summary>
        public static string lblTablaColNombreDefecto {
            get {
                return ResourceManager.GetString("lblTablaColNombreDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string lblTablaColVisible {
            get {
                return ResourceManager.GetString("lblTablaColVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Filtros.
        /// </summary>
        public static string lblTituloAsignacionFiltros {
            get {
                return ResourceManager.GetString("lblTituloAsignacionFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Nombre de Objeto.
        /// </summary>
        public static string lblTituloEditarNombreObjeto {
            get {
                return ResourceManager.GetString("lblTituloEditarNombreObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El texto que ingrese es el que va a visualizar como título para este tipo de Gráfico en el futuro..
        /// </summary>
        public static string lblTituloGraficoAviso {
            get {
                return ResourceManager.GetString("lblTituloGraficoAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede ir al listado de usuarios haciendo click.
        /// </summary>
        public static string lblUsuarioNoEncontradoLink1 {
            get {
                return ResourceManager.GetString("lblUsuarioNoEncontradoLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aquí.
        /// </summary>
        public static string lblUsuarioNoEncontradoLinkAqui {
            get {
                return ResourceManager.GetString("lblUsuarioNoEncontradoLinkAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el usuario que está buscando.
        /// </summary>
        public static string lblUsuarioNoEncontradoMensaje {
            get {
                return ResourceManager.GetString("lblUsuarioNoEncontradoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esto no afectará sus datos..
        /// </summary>
        public static string lblUsuarioNoEncontradoSubTitulo {
            get {
                return ResourceManager.GetString("lblUsuarioNoEncontradoSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario No Encontrado.
        /// </summary>
        public static string lblUsuarioNoEncontradoTitulo {
            get {
                return ResourceManager.GetString("lblUsuarioNoEncontradoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string lblUsuarios {
            get {
                return ResourceManager.GetString("lblUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activando....
        /// </summary>
        public static string lblUsuariosActivando {
            get {
                return ResourceManager.GetString("lblUsuariosActivando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios y Roles.
        /// </summary>
        public static string lblUsuariosRoles {
            get {
                return ResourceManager.GetString("lblUsuariosRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de usuarios, puede modificar los atributos y asignación de rol de los usuarios.
        /// </summary>
        public static string lblUsuariosSubtitulo {
            get {
                return ResourceManager.GetString("lblUsuariosSubtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string lblUsuariosTablaColApellido {
            get {
                return ResourceManager.GetString("lblUsuariosTablaColApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblUsuariosTablaColEmail {
            get {
                return ResourceManager.GetString("lblUsuariosTablaColEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string lblUsuariosTablaColNombre {
            get {
                return ResourceManager.GetString("lblUsuariosTablaColNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string lblUsuariosTitulo {
            get {
                return ResourceManager.GetString("lblUsuariosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de Usuarios.
        /// </summary>
        public static string lblUsuariosTitulo2 {
            get {
                return ResourceManager.GetString("lblUsuariosTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Utiliza Nombre por Defecto).
        /// </summary>
        public static string lblUtilizaNombrePorDefecto {
            get {
                return ResourceManager.GetString("lblUtilizaNombrePorDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link a página personal.
        /// </summary>
        public static string linkMarcaBlancaLabel {
            get {
                return ResourceManager.GetString("linkMarcaBlancaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string logoMarcaBlancaLabel {
            get {
                return ResourceManager.GetString("logoMarcaBlancaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe crear al menos un objeto para visualizarlo.
        /// </summary>
        public static string noDataFoundViewSubTitle {
            get {
                return ResourceManager.GetString("noDataFoundViewSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron datos.
        /// </summary>
        public static string noDataFoundViewTitle {
            get {
                return ResourceManager.GetString("noDataFoundViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene cliente seleccionado, debe seleccionar uno para continuar.
        /// </summary>
        public static string noTieneClienteSeleccionado {
            get {
                return ResourceManager.GetString("noTieneClienteSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron usuarios.
        /// </summary>
        public static string noTieneUsuarios {
            get {
                return ResourceManager.GetString("noTieneUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay datos para mostrar.
        /// </summary>
        public static string noTieneUsuariosSubTitulo {
            get {
                return ResourceManager.GetString("noTieneUsuariosSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Apellido de usuario debe tener entre 3 y 30 caracteres.
        /// </summary>
        public static string PerfilApellidoErrorLength {
            get {
                return ResourceManager.GetString("PerfilApellidoErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es obligatorio especificar un Apellido de usuario.
        /// </summary>
        public static string PerfilApellidoRequiredError {
            get {
                return ResourceManager.GetString("PerfilApellidoRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Email debe tener menos de 100 caracteres.
        /// </summary>
        public static string PerfilEmailErrorLength {
            get {
                return ResourceManager.GetString("PerfilEmailErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es obligatorio especificar un Email.
        /// </summary>
        public static string PerfilEmailRequiredError {
            get {
                return ResourceManager.GetString("PerfilEmailRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Nombre de usuario debe tener entre 3 y 30 caracteres.
        /// </summary>
        public static string PerfilNombreErrorLength {
            get {
                return ResourceManager.GetString("PerfilNombreErrorLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es obligatorio especificar un Nombre de usuario.
        /// </summary>
        public static string PerfilNombreRequiredError {
            get {
                return ResourceManager.GetString("PerfilNombreRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar.
        /// </summary>
        public static string permiso_administrarTablero {
            get {
                return ResourceManager.GetString("permiso_administrarTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartir.
        /// </summary>
        public static string permiso_compartirTablero {
            get {
                return ResourceManager.GetString("permiso_compartirTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Alerta.
        /// </summary>
        public static string permiso_crearAlertas {
            get {
                return ResourceManager.GetString("permiso_crearAlertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string permiso_crearTablero {
            get {
                return ResourceManager.GetString("permiso_crearTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string permiso_descargarImagenes {
            get {
                return ResourceManager.GetString("permiso_descargarImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Alerta.
        /// </summary>
        public static string permiso_editarAlertas {
            get {
                return ResourceManager.GetString("permiso_editarAlertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string permiso_editarTablero {
            get {
                return ResourceManager.GetString("permiso_editarTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Alerta.
        /// </summary>
        public static string permiso_eliminarAlertas {
            get {
                return ResourceManager.GetString("permiso_eliminarAlertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string permiso_eliminarTablero {
            get {
                return ResourceManager.GetString("permiso_eliminarTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Alerta.
        /// </summary>
        public static string permiso_verAlertas {
            get {
                return ResourceManager.GetString("permiso_verAlertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string permiso_verDatos {
            get {
                return ResourceManager.GetString("permiso_verDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string permiso_verImagenes {
            get {
                return ResourceManager.GetString("permiso_verImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string permiso_verMapas {
            get {
                return ResourceManager.GetString("permiso_verMapas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string permiso_verTablero {
            get {
                return ResourceManager.GetString("permiso_verTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar objeto por nombre....
        /// </summary>
        public static string placeholderAsignacionObjetosBuscar {
            get {
                return ResourceManager.GetString("placeholderAsignacionObjetosBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar objeto por nombre....
        /// </summary>
        public static string placeholderConfigurarObjetosSearch {
            get {
                return ResourceManager.GetString("placeholderConfigurarObjetosSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre personalizado de Filtro.
        /// </summary>
        public static string placeholderNombrePersonalizadoFiltro {
            get {
                return ResourceManager.GetString("placeholderNombrePersonalizadoFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar roles....
        /// </summary>
        public static string placeholderRolesBuscar {
            get {
                return ResourceManager.GetString("placeholderRolesBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar filtro por nombre....
        /// </summary>
        public static string placeholderSearchNombreFiltro {
            get {
                return ResourceManager.GetString("placeholderSearchNombreFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Módulo.
        /// </summary>
        public static string placeholderSeleccionModulo {
            get {
                return ResourceManager.GetString("placeholderSeleccionModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar usuarios....
        /// </summary>
        public static string placeholderUsuariosBuscar {
            get {
                return ResourceManager.GetString("placeholderUsuariosBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor revise si los datos son correctos.
        /// </summary>
        public static string reviseSiDatosSonCorrectos {
            get {
                return ResourceManager.GetString("reviseSiDatosSonCorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Rol.
        /// </summary>
        public static string seleccionUnRol {
            get {
                return ResourceManager.GetString("seleccionUnRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración guardada con éxito.
        /// </summary>
        public static string successMarcaBlanca {
            get {
                return ResourceManager.GetString("successMarcaBlanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar Foto.
        /// </summary>
        public static string tooltipBorrarFoto {
            get {
                return ResourceManager.GetString("tooltipBorrarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño máximo es de 300kb. Resolucion recomendad: 1366 x 768..
        /// </summary>
        public static string tooltipSizeResFondo {
            get {
                return ResourceManager.GetString("tooltipSizeResFondo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño máximo es de 100kb. Resolucion recomendad: 1366 x 100..
        /// </summary>
        public static string tooltipSizeResFooter {
            get {
                return ResourceManager.GetString("tooltipSizeResFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño máximo es de 100kb. Resolucion recomendad: 140 x 40..
        /// </summary>
        public static string tooltipSizeResLogo {
            get {
                return ResourceManager.GetString("tooltipSizeResLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario debe tener un Email válido para generar el usuario de Reporting.
        /// </summary>
        public static string usuarioDebeTenerMailValido {
            get {
                return ResourceManager.GetString("usuarioDebeTenerMailValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        public static string usuarioNoEncontrado {
            get {
                return ResourceManager.GetString("usuarioNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Utiliza Nombre por Defecto).
        /// </summary>
        public static string utilizaNombrePorDefecto {
            get {
                return ResourceManager.GetString("utilizaNombrePorDefecto", resourceCulture);
            }
        }
    }
}
