//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Filtros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filtros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Filtros", typeof(Filtros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco.
        /// </summary>
        public static string fltBanco {
            get {
                return ResourceManager.GetString("fltBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadenas.
        /// </summary>
        public static string fltCadenas {
            get {
                return ResourceManager.GetString("fltCadenas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string fltCategoria {
            get {
                return ResourceManager.GetString("fltCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Producto.
        /// </summary>
        public static string fltCategoriaProducto {
            get {
                return ResourceManager.GetString("fltCategoriaProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string fltClientes {
            get {
                return ResourceManager.GetString("fltClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competencia Primaria.
        /// </summary>
        public static string fltCompetenciaPrimaria {
            get {
                return ResourceManager.GetString("fltCompetenciaPrimaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo.
        /// </summary>
        public static string fltEquipo {
            get {
                return ResourceManager.GetString("fltEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia Productos.
        /// </summary>
        public static string fltFamilia {
            get {
                return ResourceManager.GetString("fltFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Reporte.
        /// </summary>
        public static string fltFechaReporte {
            get {
                return ResourceManager.GetString("fltFechaReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jefe Gestion.
        /// </summary>
        public static string fltJefeGestion {
            get {
                return ResourceManager.GetString("fltJefeGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jefe Zonal.
        /// </summary>
        public static string fltJefeZonal {
            get {
                return ResourceManager.GetString("fltJefeZonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidades.
        /// </summary>
        public static string fltLocalidades {
            get {
                return ResourceManager.GetString("fltLocalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca Propiedad.
        /// </summary>
        public static string fltMarcaPropiedad {
            get {
                return ResourceManager.GetString("fltMarcaPropiedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcas.
        /// </summary>
        public static string fltMarcas {
            get {
                return ResourceManager.GetString("fltMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcas.
        /// </summary>
        public static string fltMarcasEpson {
            get {
                return ResourceManager.GetString("fltMarcasEpson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string fltPais {
            get {
                return ResourceManager.GetString("fltPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        public static string fltPop {
            get {
                return ResourceManager.GetString("fltPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string fltProductos {
            get {
                return ResourceManager.GetString("fltProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincias.
        /// </summary>
        public static string fltProvincias {
            get {
                return ResourceManager.GetString("fltProvincias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos de Venta.
        /// </summary>
        public static string fltPuntosDeVenta {
            get {
                return ResourceManager.GetString("fltPuntosDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de RTM.
        /// </summary>
        public static string fltRTM {
            get {
                return ResourceManager.GetString("fltRTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semaforo Distribución Física.
        /// </summary>
        public static string fltSemaforoTrade {
            get {
                return ResourceManager.GetString("fltSemaforoTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Categoria.
        /// </summary>
        public static string fltSubCategoria {
            get {
                return ResourceManager.GetString("fltSubCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucursal.
        /// </summary>
        public static string fltSucursal {
            get {
                return ResourceManager.GetString("fltSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string fltTags {
            get {
                return ResourceManager.GetString("fltTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Cadena.
        /// </summary>
        public static string fltTipoCadena {
            get {
                return ResourceManager.GetString("fltTipoCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de RTM.
        /// </summary>
        public static string fltTipoDeRTM {
            get {
                return ResourceManager.GetString("fltTipoDeRTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de entrega.
        /// </summary>
        public static string fltTipoEntrega {
            get {
                return ResourceManager.GetString("fltTipoEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Punto de Venta.
        /// </summary>
        public static string fltTipoPDV {
            get {
                return ResourceManager.GetString("fltTipoPDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Sucursal.
        /// </summary>
        public static string fltTipoSucursal {
            get {
                return ResourceManager.GetString("fltTipoSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string fltUsuarios {
            get {
                return ResourceManager.GetString("fltUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendedores.
        /// </summary>
        public static string fltVendedores {
            get {
                return ResourceManager.GetString("fltVendedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zonas.
        /// </summary>
        public static string fltZonas {
            get {
                return ResourceManager.GetString("fltZonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Filtros.
        /// </summary>
        public static string lblEliminarFiltros {
            get {
                return ResourceManager.GetString("lblEliminarFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FiltrosAplicados.
        /// </summary>
        public static string lblFiltrosAplicados {
            get {
                return ResourceManager.GetString("lblFiltrosAplicados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes Actual.
        /// </summary>
        public static string lblMesActual {
            get {
                return ResourceManager.GetString("lblMesActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar Filtros.
        /// </summary>
        public static string linkAplicarFiltro {
            get {
                return ResourceManager.GetString("linkAplicarFiltro", resourceCulture);
            }
        }
    }
}
