//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Forecasting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Forecasting() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Forecasting", typeof(Forecasting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string aceptar {
            get {
                return ResourceManager.GetString("aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cadena.
        /// </summary>
        public static string cadena {
            get {
                return ResourceManager.GetString("cadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canal.
        /// </summary>
        public static string canal {
            get {
                return ResourceManager.GetString("canal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canal:.
        /// </summary>
        public static string canales_seleccionados {
            get {
                return ResourceManager.GetString("canales_seleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando formularios....
        /// </summary>
        public static string cargando_formularios {
            get {
                return ResourceManager.GetString("cargando_formularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        public static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string cliente {
            get {
                return ResourceManager.GetString("cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmado.
        /// </summary>
        public static string confirmado {
            get {
                return ResourceManager.GetString("confirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string confirmar {
            get {
                return ResourceManager.GetString("confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Forecast.
        /// </summary>
        public static string confirmar_mes {
            get {
                return ResourceManager.GetString("confirmar_mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta.
        /// </summary>
        public static string cuenta {
            get {
                return ResourceManager.GetString("cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas seleccionadas:.
        /// </summary>
        public static string cuentas_seleccionadas {
            get {
                return ResourceManager.GetString("cuentas_seleccionadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un canal.
        /// </summary>
        public static string debe_seleccionar_canal {
            get {
                return ResourceManager.GetString("debe_seleccionar_canal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos una cuenta.
        /// </summary>
        public static string debe_seleccionar_cuenta {
            get {
                return ResourceManager.GetString("debe_seleccionar_cuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un producto.
        /// </summary>
        public static string debe_seleccionar_producto {
            get {
                return ResourceManager.GetString("debe_seleccionar_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloquear.
        /// </summary>
        public static string desbloquear {
            get {
                return ResourceManager.GetString("desbloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar guardar los datos de forecasting.
        /// </summary>
        public static string error_al_intentar_guardar_datos_de_formulario {
            get {
                return ResourceManager.GetString("error_al_intentar_guardar_datos_de_formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar xls.
        /// </summary>
        public static string exportar_xls {
            get {
                return ResourceManager.GetString("exportar_xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación.
        /// </summary>
        public static string facturacion {
            get {
                return ResourceManager.GetString("facturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Confirmación.
        /// </summary>
        public static string fecha_confirmacion {
            get {
                return ResourceManager.GetString("fecha_confirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardando datos de formulario....
        /// </summary>
        public static string guardando_datos_de_formulario {
            get {
                return ResourceManager.GetString("guardando_datos_de_formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string guardar_cambios {
            get {
                return ResourceManager.GetString("guardar_cambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial.
        /// </summary>
        public static string historial {
            get {
                return ResourceManager.GetString("historial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso de datos para Sales In/Sales out.
        /// </summary>
        public static string ingreso_de_datos_para_sales_in_out {
            get {
                return ResourceManager.GetString("ingreso_de_datos_para_sales_in_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de CAP confirmados por vendedores, puede ingresar a cada uno y ver los valores de Sales In y Sales Out ingresados y/o desbloquear el registro para poder editar estos valores..
        /// </summary>
        public static string lista_de_psi_confirmados_por_vendedores {
            get {
                return ResourceManager.GetString("lista_de_psi_confirmados_por_vendedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Detalle.
        /// </summary>
        public static string mostrar_detalle {
            get {
                return ResourceManager.GetString("mostrar_detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Futuro.
        /// </summary>
        public static string mostrar_futuro {
            get {
                return ResourceManager.GetString("mostrar_futuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar Histórico.
        /// </summary>
        public static string mostrar_historico {
            get {
                return ResourceManager.GetString("mostrar_historico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar totales.
        /// </summary>
        public static string mostrar_totales {
            get {
                return ResourceManager.GetString("mostrar_totales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún dato de Channel Inv puede ser menor a 0.
        /// </summary>
        public static string ningun_dato_de_channel_inv_puede_ser_menor_a_0 {
            get {
                return ResourceManager.GetString("ningun_dato_de_channel_inv_puede_ser_menor_a_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede ser vacío.
        /// </summary>
        public static string no_puede_ser_vacio {
            get {
                return ResourceManager.GetString("no_puede_ser_vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-OUT no puede ser 0 si hay inventario en el ultimo mes.
        /// </summary>
        public static string no_sales_out {
            get {
                return ResourceManager.GetString("no_sales_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron formularios de modelos para continuar.
        /// </summary>
        public static string no_se_encontraron_formularios {
            get {
                return ResourceManager.GetString("no_se_encontraron_formularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró ningún canal asociado a su usuario en base a los clientes que tiene asignados..
        /// </summary>
        public static string no_se_encontro_ningun_canal_asociado {
            get {
                return ResourceManager.GetString("no_se_encontro_ningun_canal_asociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudieron cargar los formularios..
        /// </summary>
        public static string no_se_pudieron_cargar_formularios {
            get {
                return ResourceManager.GetString("no_se_pudieron_cargar_formularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene Canales asignados.
        /// </summary>
        public static string no_tiene_canales_asignados {
            get {
                return ResourceManager.GetString("no_tiene_canales_asignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string observaciones {
            get {
                return ResourceManager.GetString("observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar Detalle.
        /// </summary>
        public static string ocultar_detalle {
            get {
                return ResourceManager.GetString("ocultar_detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar Futuro.
        /// </summary>
        public static string ocultar_futuro {
            get {
                return ResourceManager.GetString("ocultar_futuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar Histórico.
        /// </summary>
        public static string ocultar_historico {
            get {
                return ResourceManager.GetString("ocultar_historico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación.
        /// </summary>
        public static string operacion {
            get {
                return ResourceManager.GetString("operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        public static string producto {
            get {
                return ResourceManager.GetString("producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAP Confirmados.
        /// </summary>
        public static string psi_confirmados {
            get {
                return ResourceManager.GetString("psi_confirmados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revenue Total.
        /// </summary>
        public static string revenue_total {
            get {
                return ResourceManager.GetString("revenue_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SI.
        /// </summary>
        public static string si {
            get {
                return ResourceManager.GetString("si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione una cuenta para ingresar los valores de Sales In y Sales Out.
        /// </summary>
        public static string subtitle {
            get {
                return ResourceManager.GetString("subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAP.
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        public static string todos {
            get {
                return ResourceManager.GetString("todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Varios.
        /// </summary>
        public static string varios {
            get {
                return ResourceManager.GetString("varios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string ver {
            get {
                return ResourceManager.GetString("ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string volver {
            get {
                return ResourceManager.GetString("volver", resourceCulture);
            }
        }
    }
}
