//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Graficos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Graficos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Graficos", typeof(Graficos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share Aceites Maiz.
        /// </summary>
        public static string AGDShelfShareAceitesMaiz {
            get {
                return ResourceManager.GetString("AGDShelfShareAceitesMaiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share Aceites Tradicionalas.
        /// </summary>
        public static string AGDShelfShareAceitesTrad {
            get {
                return ResourceManager.GetString("AGDShelfShareAceitesTrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share por Familia.
        /// </summary>
        public static string AGDShelfShareFamilia {
            get {
                return ResourceManager.GetString("AGDShelfShareFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share Ketchup.
        /// </summary>
        public static string AGDShelfShareKetchup {
            get {
                return ResourceManager.GetString("AGDShelfShareKetchup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share Mayonesas.
        /// </summary>
        public static string AGDShelfShareMayonesas {
            get {
                return ResourceManager.GetString("AGDShelfShareMayonesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share Mostaza.
        /// </summary>
        public static string AGDShelfShareMostaza {
            get {
                return ResourceManager.GetString("AGDShelfShareMostaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share Olivados.
        /// </summary>
        public static string AGDShelfShareOlivados {
            get {
                return ResourceManager.GetString("AGDShelfShareOlivados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share Olivas Extra Virgen.
        /// </summary>
        public static string AGDShelfShareOlivasExtra {
            get {
                return ResourceManager.GetString("AGDShelfShareOlivasExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share Rocios.
        /// </summary>
        public static string AGDShelfShareRocios {
            get {
                return ResourceManager.GetString("AGDShelfShareRocios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share Salsa Golf.
        /// </summary>
        public static string AGDShelfShareSalsaGolf {
            get {
                return ResourceManager.GetString("AGDShelfShareSalsaGolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Permanencia.
        /// </summary>
        public static string AndromacoPermanenciaPDV2doNivel {
            get {
                return ResourceManager.GetString("AndromacoPermanenciaPDV2doNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiebre y Frentes por Productos.
        /// </summary>
        public static string aventFarmacityQuiebreFrente {
            get {
                return ResourceManager.GetString("aventFarmacityQuiebreFrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos de Venta con Distribucion por Familia.
        /// </summary>
        public static string AventPdvDistribucionFamilia {
            get {
                return ResourceManager.GetString("AventPdvDistribucionFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Pop antes y despues de visita.
        /// </summary>
        public static string BaytonDetallePop {
            get {
                return ResourceManager.GetString("BaytonDetallePop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos BROTHER.
        /// </summary>
        public static string BROTHERImg {
            get {
                return ResourceManager.GetString("BROTHERImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de Producto por Proyecto.
        /// </summary>
        public static string CambioDeProductoPorProyecto {
            get {
                return ResourceManager.GetString("CambioDeProductoPorProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de Productos por Categoria.
        /// </summary>
        public static string CambioDeProductosPorCategoria {
            get {
                return ResourceManager.GetString("CambioDeProductosPorCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos CANON.
        /// </summary>
        public static string CANONImg {
            get {
                return ResourceManager.GetString("CANONImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant. de bandejas de flanes.
        /// </summary>
        public static string CantDeBandejasF {
            get {
                return ResourceManager.GetString("CantDeBandejasF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant. de bandejas de postres.
        /// </summary>
        public static string CantDeBandejasP {
            get {
                return ResourceManager.GetString("CantDeBandejasP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant. de bandejas de yogurt descremado.
        /// </summary>
        public static string CantDeBandejasYD {
            get {
                return ResourceManager.GetString("CantDeBandejasYD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant. de bandejas de yogurt entero.
        /// </summary>
        public static string CantDeBandejasYE {
            get {
                return ResourceManager.GetString("CantDeBandejasYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant.de gondolas ARSA-DANONE-OTRAS MARCAS.
        /// </summary>
        public static string CantDeGondolasDetalle {
            get {
                return ResourceManager.GetString("CantDeGondolasDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de variedad.
        /// </summary>
        public static string CantidadDeVariedad {
            get {
                return ResourceManager.GetString("CantidadDeVariedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de variedades en gondolas .
        /// </summary>
        public static string CantidadDeVariedadesEnGondolas {
            get {
                return ResourceManager.GetString("CantidadDeVariedadesEnGondolas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacitaciones por Categoria.
        /// </summary>
        public static string CapacitacionesPorCategoria {
            get {
                return ResourceManager.GetString("CapacitacionesPorCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacitados por TP.
        /// </summary>
        public static string CapacitadosPorCadena {
            get {
                return ResourceManager.GetString("CapacitadosPorCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje Acumulado Mensual .
        /// </summary>
        public static string CMAcumuladoMensual {
            get {
                return ResourceManager.GetString("CMAcumuladoMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COB-DIST SIN EXH-QUIEBRE.
        /// </summary>
        public static string Cob_distSinExh {
            get {
                return ResourceManager.GetString("Cob_distSinExh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cob-Dist-SinExh-quiebre(tabla).
        /// </summary>
        public static string CobDistSinExhquiebretabla {
            get {
                return ResourceManager.GetString("CobDistSinExhquiebretabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobertura  y cumplimiento calendario.
        /// </summary>
        public static string Cobertura_cumplimiento_calendario {
            get {
                return ResourceManager.GetString("Cobertura_cumplimiento_calendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cumplimiento Planograma.
        /// </summary>
        public static string Cumplimiento_Planograma {
            get {
                return ResourceManager.GetString("Cumplimiento_Planograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Quiebre de Stock.
        /// </summary>
        public static string Detalle_de_Quiebre_de_Stock {
            get {
                return ResourceManager.GetString("Detalle_de_Quiebre_de_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje de Exhibidores.
        /// </summary>
        public static string Detalle_Exhibidores {
            get {
                return ResourceManager.GetString("Detalle_Exhibidores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Perfomance ventas por Usuario.
        /// </summary>
        public static string Detalle_Perfomance_ventas_por_Usuario {
            get {
                return ResourceManager.GetString("Detalle_Perfomance_ventas_por_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Pop-Cobertura-Objetivos.
        /// </summary>
        public static string Detalle_Pop_Cobertura_Objetivo {
            get {
                return ResourceManager.GetString("Detalle_Pop_Cobertura_Objetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Check in-Check Out.
        /// </summary>
        public static string DetalleCheckinCheckOut {
            get {
                return ResourceManager.GetString("DetalleCheckinCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de la Competencia.
        /// </summary>
        public static string DetalleDeLaCompetencia {
            get {
                return ResourceManager.GetString("DetalleDeLaCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de Permanencia.
        /// </summary>
        public static string DetalleDePermanencia {
            get {
                return ResourceManager.GetString("DetalleDePermanencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de respuesta sobre las preguntas Gondolas.
        /// </summary>
        public static string DetalleDeRespuestaDePreguntasGondolas {
            get {
                return ResourceManager.GetString("DetalleDeRespuestaDePreguntasGondolas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Precio Propio 3.
        /// </summary>
        public static string DetallePrecioPropio3 {
            get {
                return ResourceManager.GetString("DetallePrecioPropio3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle preguntas punteras.
        /// </summary>
        public static string DetallePreguntaspunteras {
            get {
                return ResourceManager.GetString("DetallePreguntaspunteras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de productos en buen estado y mal estado.
        /// </summary>
        public static string DetalleProductosConEstados {
            get {
                return ResourceManager.GetString("DetalleProductosConEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle relevo.
        /// </summary>
        public static string DetalleRelevo {
            get {
                return ResourceManager.GetString("DetalleRelevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Fisica Numérica Producto.
        /// </summary>
        public static string Distribucion_Fisica_Producto {
            get {
                return ResourceManager.GetString("Distribucion_Fisica_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribucion Fisica Numérica (Barras).
        /// </summary>
        public static string DistribucionFisicaNumerica {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Física Numérica Cadena.
        /// </summary>
        public static string DistribucionFisicaNumericaCadena {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumericaCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Física Numérica Cadena por Mes.
        /// </summary>
        public static string DistribucionFisicaNumericaCadenaMes {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumericaCadenaMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Física Numérica Cocinas (Barras).
        /// </summary>
        public static string DistribucionFisicaNumericaCocinas {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumericaCocinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Física Numérica Cocinas (PY).
        /// </summary>
        public static string DistribucionFisicaNumericaCocinasPY {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumericaCocinasPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribucion Fisica Numérica Competencia (Barras).
        /// </summary>
        public static string DistribucionFisicaNumericaCompetencia {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumericaCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Física Numérica Heladeras (Barras).
        /// </summary>
        public static string DistribucionFisicaNumericaHeladeras {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumericaHeladeras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Física Numérica Heladeras (PY).
        /// </summary>
        public static string DistribucionFisicaNumericaHeladerasPY {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumericaHeladerasPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Física Numérica Lavado (Barras).
        /// </summary>
        public static string DistribucionFisicaNumericaLavado {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumericaLavado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Física Numérica Lavado (PY).
        /// </summary>
        public static string DistribucionFisicaNumericaLavadoPY {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumericaLavadoPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribucion Fisica Numérica Productos (Barras).
        /// </summary>
        public static string DistribucionFisicaNumericaProductos {
            get {
                return ResourceManager.GetString("DistribucionFisicaNumericaProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DF x Proyecto y Usuario.
        /// </summary>
        public static string DistribucionFisicaPorFamilia {
            get {
                return ResourceManager.GetString("DistribucionFisicaPorFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte Precios Competencia CO.
        /// </summary>
        public static string EddingPreciosCompetenciaCO {
            get {
                return ResourceManager.GetString("EddingPreciosCompetenciaCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ElectroLux Floor Space.
        /// </summary>
        public static string ElectroLux_Floor_Space {
            get {
                return ResourceManager.GetString("ElectroLux_Floor_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electrolux Floor Space Freezer.
        /// </summary>
        public static string Electrolux_Floor_Space_Freezer1 {
            get {
                return ResourceManager.GetString("Electrolux_Floor_Space_Freezer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electrolux Floor Space Ranges.
        /// </summary>
        public static string Electrolux_Floor_Space_Ranges {
            get {
                return ResourceManager.GetString("Electrolux_Floor_Space_Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electrolux Floor Space Refrigerators.
        /// </summary>
        public static string Electrolux_Floor_Space_Refrigerators {
            get {
                return ResourceManager.GetString("Electrolux_Floor_Space_Refrigerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electrolux Floor Space Washers.
        /// </summary>
        public static string Electrolux_Floor_Space_Washers {
            get {
                return ResourceManager.GetString("Electrolux_Floor_Space_Washers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuesta Completa BaytonTarjetaNaranja.
        /// </summary>
        public static string EncuestaCompletaBaytonTarjetaNaranja {
            get {
                return ResourceManager.GetString("EncuestaCompletaBaytonTarjetaNaranja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Channel Sell-In Dist/Ret.
        /// </summary>
        public static string EPSON_ChannelSellIn_T12 {
            get {
                return ResourceManager.GetString("EPSON_ChannelSellIn_T12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobertura y objetivo por cadena .
        /// </summary>
        public static string Epson_CoberturaObjetivoRetail {
            get {
                return ResourceManager.GetString("Epson_CoberturaObjetivoRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forecast Accuracy | Sales Team.
        /// </summary>
        public static string EPSON_PerformanceClienteVendedor_T26 {
            get {
                return ResourceManager.GetString("EPSON_PerformanceClienteVendedor_T26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propuesta F19.
        /// </summary>
        public static string Epson_ProposalF19 {
            get {
                return ResourceManager.GetString("Epson_ProposalF19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PSI Histórico vs Actual.
        /// </summary>
        public static string Epson_PSIHistoricoVsActual {
            get {
                return ResourceManager.GetString("Epson_PSIHistoricoVsActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PSI Simulation.
        /// </summary>
        public static string EPSON_PSISimulation_T19 {
            get {
                return ResourceManager.GetString("EPSON_PSISimulation_T19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visitas por Retail.
        /// </summary>
        public static string EpsonCadena {
            get {
                return ResourceManager.GetString("EpsonCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Channel Mix (CONS).
        /// </summary>
        public static string EpsonChannelMixCONS {
            get {
                return ResourceManager.GetString("EpsonChannelMixCONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Channel Mix (HW).
        /// </summary>
        public static string EpsonChannelMixHW {
            get {
                return ResourceManager.GetString("EpsonChannelMixHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banda de Precios - REGION.
        /// </summary>
        public static string EpsonComparacionPreciosRegional {
            get {
                return ResourceManager.GetString("EpsonComparacionPreciosRegional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competimeter.
        /// </summary>
        public static string EPSONCompetimeter {
            get {
                return ResourceManager.GetString("EPSONCompetimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Epson Competimeter Consumibles.
        /// </summary>
        public static string EPSONCompetimeterConsumibles {
            get {
                return ResourceManager.GetString("EPSONCompetimeterConsumibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country Sell-In Accuracy.
        /// </summary>
        public static string EpsonCountryAccuracy {
            get {
                return ResourceManager.GetString("EpsonCountryAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribuidor Sell-In Accuracy.
        /// </summary>
        public static string EpsonDistAccuracy {
            get {
                return ResourceManager.GetString("EpsonDistAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribucion Fisica.
        /// </summary>
        public static string EpsonDistribucionFisicaDat {
            get {
                return ResourceManager.GetString("EpsonDistribucionFisicaDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolucion de Precios  - REGION.
        /// </summary>
        public static string EpsonEvolucionPreciosRegional {
            get {
                return ResourceManager.GetString("EpsonEvolucionPreciosRegional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación.
        /// </summary>
        public static string EpsonFacturacionPSI {
            get {
                return ResourceManager.GetString("EpsonFacturacionPSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fit-Ratio (CONS).
        /// </summary>
        public static string EpsonFitRatio {
            get {
                return ResourceManager.GetString("EpsonFitRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fit Ratio Detalle.
        /// </summary>
        public static string EpsonFitRatioDetalle {
            get {
                return ResourceManager.GetString("EpsonFitRatioDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fit-Ratio Interactivo.
        /// </summary>
        public static string EpsonFitRatioHistorico {
            get {
                return ResourceManager.GetString("EpsonFitRatioHistorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos EPSON.
        /// </summary>
        public static string EPSONImg {
            get {
                return ResourceManager.GetString("EPSONImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info Nodo.
        /// </summary>
        public static string epsoninfonodo {
            get {
                return ResourceManager.GetString("epsoninfonodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventario (CONS).
        /// </summary>
        public static string EpsonInventarioCONS {
            get {
                return ResourceManager.GetString("EpsonInventarioCONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventario (HW).
        /// </summary>
        public static string EpsonInventarioHW {
            get {
                return ResourceManager.GetString("EpsonInventarioHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KPI Epson.
        /// </summary>
        public static string EpsonKPI {
            get {
                return ResourceManager.GetString("EpsonKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Market Share.
        /// </summary>
        public static string EpsonMarketShare {
            get {
                return ResourceManager.GetString("EpsonMarketShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversion.
        /// </summary>
        public static string EpsonMarketShareConversion {
            get {
                return ResourceManager.GetString("EpsonMarketShareConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Market Share YTD.
        /// </summary>
        public static string EpsonMarketShareYTD {
            get {
                return ResourceManager.GetString("EpsonMarketShareYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retail Sell-In Accuracy.
        /// </summary>
        public static string EpsonRetailAccuracy {
            get {
                return ResourceManager.GetString("EpsonRetailAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In CISS.
        /// </summary>
        public static string EpsonSellInCISS {
            get {
                return ResourceManager.GetString("EpsonSellInCISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In CISS MoM.
        /// </summary>
        public static string EpsonSellInCISSMoM {
            get {
                return ResourceManager.GetString("EpsonSellInCISSMoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In CISS YoY.
        /// </summary>
        public static string EpsonSellInCISSYoY {
            get {
                return ResourceManager.GetString("EpsonSellInCISSYoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In CISS YTD.
        /// </summary>
        public static string EpsonSellInCISSYTD {
            get {
                return ResourceManager.GetString("EpsonSellInCISSYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In IC.
        /// </summary>
        public static string EpsonSellInIC {
            get {
                return ResourceManager.GetString("EpsonSellInIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In IC MoM.
        /// </summary>
        public static string EpsonSellInICMoM {
            get {
                return ResourceManager.GetString("EpsonSellInICMoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In IC YoY.
        /// </summary>
        public static string EpsonSellInICYoY {
            get {
                return ResourceManager.GetString("EpsonSellInICYoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In IC YTD.
        /// </summary>
        public static string EpsonSellInICYTD {
            get {
                return ResourceManager.GetString("EpsonSellInICYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In IJP.
        /// </summary>
        public static string EpsonSellInIjp {
            get {
                return ResourceManager.GetString("EpsonSellInIjp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In IJP MoM.
        /// </summary>
        public static string EpsonSellInIjpMoM {
            get {
                return ResourceManager.GetString("EpsonSellInIjpMoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In IJP YoY.
        /// </summary>
        public static string EpsonSellInIjpYoY {
            get {
                return ResourceManager.GetString("EpsonSellInIjpYoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-In IJP YTD.
        /// </summary>
        public static string EpsonSellInIjpYTD {
            get {
                return ResourceManager.GetString("EpsonSellInIjpYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out CISS.
        /// </summary>
        public static string EpsonSellOutCISS {
            get {
                return ResourceManager.GetString("EpsonSellOutCISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out CISS MoM.
        /// </summary>
        public static string EpsonSellOutCISSMoM {
            get {
                return ResourceManager.GetString("EpsonSellOutCISSMoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out CISS YoY.
        /// </summary>
        public static string EpsonSellOutCISSYoY {
            get {
                return ResourceManager.GetString("EpsonSellOutCISSYoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out CISS YTD.
        /// </summary>
        public static string EpsonSellOutCISSYTD {
            get {
                return ResourceManager.GetString("EpsonSellOutCISSYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out IC.
        /// </summary>
        public static string EpsonSellOutIC {
            get {
                return ResourceManager.GetString("EpsonSellOutIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out IC MoM.
        /// </summary>
        public static string EpsonSellOutICMoM {
            get {
                return ResourceManager.GetString("EpsonSellOutICMoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out IC YoY.
        /// </summary>
        public static string EpsonSellOutICYoY {
            get {
                return ResourceManager.GetString("EpsonSellOutICYoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out IC YTD.
        /// </summary>
        public static string EpsonSellOutICYTD {
            get {
                return ResourceManager.GetString("EpsonSellOutICYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out IJP.
        /// </summary>
        public static string EpsonSellOutIjp {
            get {
                return ResourceManager.GetString("EpsonSellOutIjp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out IJP MoM.
        /// </summary>
        public static string EpsonSellOutIjpMoM {
            get {
                return ResourceManager.GetString("EpsonSellOutIjpMoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out IJP YoY.
        /// </summary>
        public static string EpsonSellOutIjpYoY {
            get {
                return ResourceManager.GetString("EpsonSellOutIjpYoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell-Out IJP YTD.
        /// </summary>
        public static string EpsonSellOutIjpYTD {
            get {
                return ResourceManager.GetString("EpsonSellOutIjpYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacitacion Epson Trade.
        /// </summary>
        public static string epsontradecapacitacion {
            get {
                return ResourceManager.GetString("epsontradecapacitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribución Física.
        /// </summary>
        public static string EpsonTradeDistribucionFisica {
            get {
                return ResourceManager.GetString("EpsonTradeDistribucionFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades (CONS).
        /// </summary>
        public static string EpsonUnidadesCONS {
            get {
                return ResourceManager.GetString("EpsonUnidadesCONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades (HW).
        /// </summary>
        public static string EpsonUnidadesHW {
            get {
                return ResourceManager.GetString("EpsonUnidadesHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Var Sell-In Sell-Out DIST.
        /// </summary>
        public static string EpsonVarSellInSellOutDist {
            get {
                return ResourceManager.GetString("EpsonVarSellInSellOutDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Var Sell-In Sell-Out RET.
        /// </summary>
        public static string EpsonVarSellInSellOutRet {
            get {
                return ResourceManager.GetString("EpsonVarSellInSellOutRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas por PDV.
        /// </summary>
        public static string epsonventasporpdv {
            get {
                return ResourceManager.GetString("epsonventasporpdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas por Producto.
        /// </summary>
        public static string epsonventasproducto {
            get {
                return ResourceManager.GetString("epsonventasproducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluacion de Desempeño del Equipo.
        /// </summary>
        public static string EvaluacionDeAuditoriaDeDesempeño {
            get {
                return ResourceManager.GetString("EvaluacionDeAuditoriaDeDesempeño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolución de Precio Promocional.
        /// </summary>
        public static string Evolucion_de_Precio_Promocional {
            get {
                return ResourceManager.GetString("Evolucion_de_Precio_Promocional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolución de Precio Lista.
        /// </summary>
        public static string Evolucion_Precio_propio_y_competencia {
            get {
                return ResourceManager.GetString("Evolucion_Precio_propio_y_competencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gap Precios propios y sugeridos.
        /// </summary>
        public static string GapPreciosPropiosSugerido {
            get {
                return ResourceManager.GetString("GapPreciosPropiosSugerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Logró instalar la pieza satisfactoriamente?.
        /// </summary>
        public static string Geometry_Instalacion {
            get {
                return ResourceManager.GetString("Geometry_Instalacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Le gusta el POP al tendero?.
        /// </summary>
        public static string Geometry_Pop {
            get {
                return ResourceManager.GetString("Geometry_Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Actualmente el tendero cuenta con producto B&amp;W?.
        /// </summary>
        public static string Geometry_Productos {
            get {
                return ResourceManager.GetString("Geometry_Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay alguna referencia de Sancor Bebe 4?.
        /// </summary>
        public static string Hay_alguna_referencia_de_Sancor_Bebe {
            get {
                return ResourceManager.GetString("Hay_alguna_referencia_de_Sancor_Bebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos HP.
        /// </summary>
        public static string HPImg {
            get {
                return ResourceManager.GetString("HPImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso autorizado al local.
        /// </summary>
        public static string Ingreso_Autorizado_Al_Local {
            get {
                return ResourceManager.GetString("Ingreso_Autorizado_Al_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Isdin LAM ReporteNuevo.
        /// </summary>
        public static string Isdin_LAM_ReporteNuevo {
            get {
                return ResourceManager.GetString("Isdin_LAM_ReporteNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Contactos.
        /// </summary>
        public static string IsdinDetalleContactos {
            get {
                return ResourceManager.GetString("IsdinDetalleContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competimeter.
        /// </summary>
        public static string lblMesaure {
            get {
                return ResourceManager.GetString("lblMesaure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KPI.
        /// </summary>
        public static string lblSimpleKpi {
            get {
                return ResourceManager.GetString("lblSimpleKpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        public static string lblTipoArea {
            get {
                return ResourceManager.GetString("lblTipoArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columnas Apiladas.
        /// </summary>
        public static string lblTipoColApiladas {
            get {
                return ResourceManager.GetString("lblTipoColApiladas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columnas con DrillDown.
        /// </summary>
        public static string lblTipoColDrilldown {
            get {
                return ResourceManager.GetString("lblTipoColDrilldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columna.
        /// </summary>
        public static string lblTipoColumna {
            get {
                return ResourceManager.GetString("lblTipoColumna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Semicirculo.
        /// </summary>
        public static string lblTipoDoughnut {
            get {
                return ResourceManager.GetString("lblTipoDoughnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drilldown Apiladas.
        /// </summary>
        public static string lblTipoDrilldownApiladas {
            get {
                return ResourceManager.GetString("lblTipoDrilldownApiladas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drilldown Apiladas Porcentual.
        /// </summary>
        public static string lblTipoDrilldownApiladasPorc {
            get {
                return ResourceManager.GetString("lblTipoDrilldownApiladasPorc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuesta.
        /// </summary>
        public static string lblTipoEncuesta {
            get {
                return ResourceManager.GetString("lblTipoEncuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Linea.
        /// </summary>
        public static string lblTipoLinea {
            get {
                return ResourceManager.GetString("lblTipoLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pie.
        /// </summary>
        public static string lblTipoPie {
            get {
                return ResourceManager.GetString("lblTipoPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spider Web.
        /// </summary>
        public static string lblTipoSpiderWeb {
            get {
                return ResourceManager.GetString("lblTipoSpiderWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla.
        /// </summary>
        public static string lblTipoTabla {
            get {
                return ResourceManager.GetString("lblTipoTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tendencia.
        /// </summary>
        public static string lblTipoTendencia {
            get {
                return ResourceManager.GetString("lblTipoTendencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mueble Whirlpool.
        /// </summary>
        public static string Mueble_Whirlpool {
            get {
                return ResourceManager.GetString("Mueble_Whirlpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No trabaja por producto .
        /// </summary>
        public static string NoTrabajaPorProducto {
            get {
                return ResourceManager.GetString("NoTrabajaPorProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No trabaja por producto Total.
        /// </summary>
        public static string NoTrabajaProductoTotal {
            get {
                return ResourceManager.GetString("NoTrabajaProductoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos de Venta Si Tiene Foto.
        /// </summary>
        public static string PdvsSiTieneFoto {
            get {
                return ResourceManager.GetString("PdvsSiTieneFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido de Services solicitado Vs Resuelto.
        /// </summary>
        public static string PedidoDeServices {
            get {
                return ResourceManager.GetString("PedidoDeServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido de Services por Categoria.
        /// </summary>
        public static string PedidoDeServicesPorCategoria {
            get {
                return ResourceManager.GetString("PedidoDeServicesPorCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfomance ventas por usuario.
        /// </summary>
        public static string PerfomanceVentasPorUsuario {
            get {
                return ResourceManager.GetString("PerfomanceVentasPorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pop-Cobertura-Objetivos.
        /// </summary>
        public static string Pop_Cobertura_Objetivo {
            get {
                return ResourceManager.GetString("Pop_Cobertura_Objetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a POP por cadena y Marca.
        /// </summary>
        public static string POP_Por_Cadena_Marca {
            get {
                return ResourceManager.GetString("POP_Por_Cadena_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pop x Marca Con Mes.
        /// </summary>
        public static string PopXMarcaConMes {
            get {
                return ResourceManager.GetString("PopXMarcaConMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Entrada/Salida Competencia por Cadena.
        /// </summary>
        public static string PrecioEntradaSalidaCompetenciaCadena {
            get {
                return ResourceManager.GetString("PrecioEntradaSalidaCompetenciaCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las 3 Categ. ARSA, están al lado de DANONE?.
        /// </summary>
        public static string PreguntasGondolasPorCategoria {
            get {
                return ResourceManager.GetString("PreguntasGondolasPorCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunicación de marca con POP?.
        /// </summary>
        public static string PreguntasGondolasPorMarca {
            get {
                return ResourceManager.GetString("PreguntasGondolasPorMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos ARSA precio en el fleje segun ubic..
        /// </summary>
        public static string PreguntasGondolasPorProductos {
            get {
                return ResourceManager.GetString("PreguntasGondolasPorProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos Arsa con fecha de venc. menor a 8 dias.
        /// </summary>
        public static string PreguntasGondolasVencimiento {
            get {
                return ResourceManager.GetString("PreguntasGondolasVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuantas Punteras hay con yog\post\flanes de ARSA?.
        /// </summary>
        public static string PreguntasPunterasArsa {
            get {
                return ResourceManager.GetString("PreguntasPunterasArsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del ploteo o revestimiento ARSA.
        /// </summary>
        public static string PreguntasPunterasEstado {
            get {
                return ResourceManager.GetString("PreguntasPunterasEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Las punteras tienen ploteos o revestimientos marca ARSA?.
        /// </summary>
        public static string PreguntasPunterasMarca {
            get {
                return ResourceManager.GetString("PreguntasPunterasMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Las punteras existentes tienen prod.ARSA?.
        /// </summary>
        public static string PreguntasPunterasProductos {
            get {
                return ResourceManager.GetString("PreguntasPunterasProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuantas Punteras hay con yog\post\flan en TOTAL?.
        /// </summary>
        public static string PreguntasPunterasTotal {
            get {
                return ResourceManager.GetString("PreguntasPunterasTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está Presente en la Etapa 1, 2 y 3 de Sancor Bebe?.
        /// </summary>
        public static string Presente_En_Simultáneo_La_Etapa {
            get {
                return ResourceManager.GetString("Presente_En_Simultáneo_La_Etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiebre Exhibicion Vs Exhibido.
        /// </summary>
        public static string QuiebreExhibicionVsExhibido {
            get {
                return ResourceManager.GetString("QuiebreExhibicionVsExhibido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relevo MD.
        /// </summary>
        public static string Relevo_MD {
            get {
                return ResourceManager.GetString("Relevo_MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repuesto Solicitado Vs Resuelto.
        /// </summary>
        public static string RepuestoSolicitadoVsResuelto {
            get {
                return ResourceManager.GetString("RepuestoSolicitadoVsResuelto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repuestos Solicitados por Categoria.
        /// </summary>
        public static string RepuestosSolicitadosPorCategoria {
            get {
                return ResourceManager.GetString("RepuestosSolicitadosPorCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repuestos Solicitados por Proyecto.
        /// </summary>
        public static string RepuestosSolicitadosPorProyecto {
            get {
                return ResourceManager.GetString("RepuestosSolicitadosPorProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retiro de Productos Solicitados Vs Resuelto.
        /// </summary>
        public static string RetiroDeProductos {
            get {
                return ResourceManager.GetString("RetiroDeProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay Sancor Bebe 1L, 500 Ml y 200 Ml en simultáneo?.
        /// </summary>
        public static string Sancor_Bebe_Simultáneo {
            get {
                return ResourceManager.GetString("Sancor_Bebe_Simultáneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobertura Cliente.
        /// </summary>
        public static string SavantCoberturaCliente {
            get {
                return ResourceManager.GetString("SavantCoberturaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobertura Zona Usuario.
        /// </summary>
        public static string SavantCoberturaZonaUsuario {
            get {
                return ResourceManager.GetString("SavantCoberturaZonaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobertura Zona Usuario (Torta).
        /// </summary>
        public static string SavantCoberturaZonaUsuarioPie {
            get {
                return ResourceManager.GetString("SavantCoberturaZonaUsuarioPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facing Marca Propia.
        /// </summary>
        public static string SavantFacingMarcaPropia {
            get {
                return ResourceManager.GetString("SavantFacingMarcaPropia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facing Marca Propia (Barras).
        /// </summary>
        public static string SavantFacingMarcaPropiaBarra {
            get {
                return ResourceManager.GetString("SavantFacingMarcaPropiaBarra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Savant No trabaja por Marca Total.
        /// </summary>
        public static string SavantNoTrabajaPorMarcaTotal {
            get {
                return ResourceManager.GetString("SavantNoTrabajaPorMarcaTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SavantNoTrabajaPorMarcaTotalBarra.
        /// </summary>
        public static string SavantNoTrabajaPorMarcaTotalBarra {
            get {
                return ResourceManager.GetString("SavantNoTrabajaPorMarcaTotalBarra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pdv Asignados por Mes.
        /// </summary>
        public static string SavantPdvAsignadosMes {
            get {
                return ResourceManager.GetString("SavantPdvAsignadosMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos de Venta con Distribucion por Zona.
        /// </summary>
        public static string SavantPdvDistribucionZona {
            get {
                return ResourceManager.GetString("SavantPdvDistribucionZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos de Venta con Distribucion por Producto/Zona.
        /// </summary>
        public static string SavantProductoDistribucionZona {
            get {
                return ResourceManager.GetString("SavantProductoDistribucionZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiebre por Equipo/Marca.
        /// </summary>
        public static string SavantQuiebreEquipoMarca {
            get {
                return ResourceManager.GetString("SavantQuiebreEquipoMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiebre Por Equipo/Marca (Barras).
        /// </summary>
        public static string SavantQuiebreEquipoMarcaBarras {
            get {
                return ResourceManager.GetString("SavantQuiebreEquipoMarcaBarras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Savant Quiebre Por Marca Total.
        /// </summary>
        public static string SavantQuiebreMarcaTotal {
            get {
                return ResourceManager.GetString("SavantQuiebreMarcaTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Savant Quiebre Por Marca Total (Barras).
        /// </summary>
        public static string SavantQuiebreMarcaTotalBarra {
            get {
                return ResourceManager.GetString("SavantQuiebreMarcaTotalBarra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiebre por Producto.
        /// </summary>
        public static string SavantQuiebrePorProducto {
            get {
                return ResourceManager.GetString("SavantQuiebrePorProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiebre por Producto (Barras).
        /// </summary>
        public static string SavantQuiebrePorProductoBarras {
            get {
                return ResourceManager.GetString("SavantQuiebrePorProductoBarras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share Marca Propia.
        /// </summary>
        public static string SavantShelfShareMarcaPropia {
            get {
                return ResourceManager.GetString("SavantShelfShareMarcaPropia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se pudo colocar POP de Paw Patrol?.
        /// </summary>
        public static string Se_Pudo_Colocar_POP_De_Paw_Patrol {
            get {
                return ResourceManager.GetString("Se_Pudo_Colocar_POP_De_Paw_Patrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Services por Proyecto.
        /// </summary>
        public static string ServicesPorProyecto {
            get {
                return ResourceManager.GetString("ServicesPorProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share - Marca y Producto propio.
        /// </summary>
        public static string Shelf_Share_Producto_Propio {
            get {
                return ResourceManager.GetString("Shelf_Share_Producto_Propio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shelf Share - Marca propia vs Competencia Frentes1.
        /// </summary>
        public static string ShelfShareMarcapropiavsCompetenciaFrentes1 {
            get {
                return ResourceManager.GetString("ShelfShareMarcapropiavsCompetenciaFrentes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sodimac Cumplimiento Planograma.
        /// </summary>
        public static string SodimacCumplimientoPlanograma {
            get {
                return ResourceManager.GetString("SodimacCumplimientoPlanograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock por Marca y Producto.
        /// </summary>
        public static string StockPorMarcaYProducto {
            get {
                return ResourceManager.GetString("StockPorMarcaYProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta por Marca y Producto.
        /// </summary>
        public static string VentaPorMarcaYProducto {
            get {
                return ResourceManager.GetString("VentaPorMarcaYProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas y Stock por Producto.
        /// </summary>
        public static string VentasYStockPorProducto {
            get {
                return ResourceManager.GetString("VentasYStockPorProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VisitasPorRetail.
        /// </summary>
        public static string VisitasPorRetail {
            get {
                return ResourceManager.GetString("VisitasPorRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DF x Sku y Usuario.
        /// </summary>
        public static string WhirlPool_DF_Por_Sku_y_Usuario {
            get {
                return ResourceManager.GetString("WhirlPool_DF_Por_Sku_y_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobertura Mensual.
        /// </summary>
        public static string WhirlPoolCobMensual {
            get {
                return ResourceManager.GetString("WhirlPoolCobMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Respuestos.
        /// </summary>
        public static string WhirlPoolEstadoRepuesto {
            get {
                return ResourceManager.GetString("WhirlPoolEstadoRepuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Retiro Producto.
        /// </summary>
        public static string WhirlPoolEstadoRetiroProducto {
            get {
                return ResourceManager.GetString("WhirlPoolEstadoRetiroProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Service.
        /// </summary>
        public static string WhirlPoolEstadoService {
            get {
                return ResourceManager.GetString("WhirlPoolEstadoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolución por Plataforma.
        /// </summary>
        public static string WhirlPoolEvolucionPorPlataforma {
            get {
                return ResourceManager.GetString("WhirlPoolEvolucionPorPlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolucion por Plataforma (Tabla).
        /// </summary>
        public static string WhirlPoolEvolucionPorPlataformaTabla {
            get {
                return ResourceManager.GetString("WhirlPoolEvolucionPorPlataformaTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolución Precio vs Accionado.
        /// </summary>
        public static string WhirlPoolEvolucionPrecio1y2 {
            get {
                return ResourceManager.GetString("WhirlPoolEvolucionPrecio1y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolucion de Precio Accionado.
        /// </summary>
        public static string WhirlPoolEvolucionPrecioAccionado {
            get {
                return ResourceManager.GetString("WhirlPoolEvolucionPrecioAccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolución de Precios.
        /// </summary>
        public static string WhirlPoolEvolucionPrecios {
            get {
                return ResourceManager.GetString("WhirlPoolEvolucionPrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Floor Share.
        /// </summary>
        public static string WhirlPoolFloorShare {
            get {
                return ResourceManager.GetString("WhirlPoolFloorShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Floor Share (PY).
        /// </summary>
        public static string WhirlPoolFloorSharePY {
            get {
                return ResourceManager.GetString("WhirlPoolFloorSharePY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gap Precios.
        /// </summary>
        public static string WhirlPoolGapPrecios {
            get {
                return ResourceManager.GetString("WhirlPoolGapPrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target vs Capacitados.
        /// </summary>
        public static string Whirpool_Capacitaciones {
            get {
                return ResourceManager.GetString("Whirpool_Capacitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Auditoria Whirlpool.
        /// </summary>
        public static string Whirpool_FloorShare_Encuesta_Completa {
            get {
                return ResourceManager.GetString("Whirpool_FloorShare_Encuesta_Completa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FS categoria x Usuario.
        /// </summary>
        public static string Whirpool_FS_Por_Categoria_Cocina {
            get {
                return ResourceManager.GetString("Whirpool_FS_Por_Categoria_Cocina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target vs Capacitados por Referentes y Asesor.
        /// </summary>
        public static string WhirpoolCapacitacionesTargetAlcance {
            get {
                return ResourceManager.GetString("WhirpoolCapacitacionesTargetAlcance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluacion de Desempeño(Relacionamiento Asesor?).
        /// </summary>
        public static string WhirpoolDesempeñoAsesor {
            get {
                return ResourceManager.GetString("WhirpoolDesempeñoAsesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluacion de Desempeño(Exhibición).
        /// </summary>
        public static string WhirpoolDesempeñoExhibicion {
            get {
                return ResourceManager.GetString("WhirpoolDesempeñoExhibicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluacion de Desempeño(Limpieza).
        /// </summary>
        public static string WhirpoolDesempeñoLimpieza {
            get {
                return ResourceManager.GetString("WhirpoolDesempeñoLimpieza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluacion de Desempeño(Ejecución POP).
        /// </summary>
        public static string WhirpoolDesempeñoPOP {
            get {
                return ResourceManager.GetString("WhirpoolDesempeñoPOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluacion de Desempeño(Distribucion Fisica).
        /// </summary>
        public static string WhirpoolDistribucionFisica {
            get {
                return ResourceManager.GetString("WhirpoolDistribucionFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referentes y Asesores.
        /// </summary>
        public static string WhirpoolReferentesAsesores {
            get {
                return ResourceManager.GetString("WhirpoolReferentesAsesores", resourceCulture);
            }
        }
    }
}
