//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Imagenes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Imagenes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Imagenes", typeof(Imagenes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios:.
        /// </summary>
        public static string comentariosLabel {
            get {
                return ResourceManager.GetString("comentariosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar esta foto.
        /// </summary>
        public static string descargarFotoLabel {
            get {
                return ResourceManager.GetString("descargarFotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar fotos a 30 días.
        /// </summary>
        public static string DescargarFotos30Dias {
            get {
                return ResourceManager.GetString("DescargarFotos30Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar fotos.
        /// </summary>
        public static string DescargarFotosResultado {
            get {
                return ResourceManager.GetString("DescargarFotosResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de creación:.
        /// </summary>
        public static string fechaCreacionLabel {
            get {
                return ResourceManager.GetString("fechaCreacionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar Filtro.
        /// </summary>
        public static string lblImagenesIndexAplicarFiltro {
            get {
                return ResourceManager.GetString("lblImagenesIndexAplicarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando Filtros....
        /// </summary>
        public static string lblImagenesIndexCargandoFiltros {
            get {
                return ResourceManager.GetString("lblImagenesIndexCargandoFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generando archivo.
        /// </summary>
        public static string lblImagenesIndexGenerandoArchivo {
            get {
                return ResourceManager.GetString("lblImagenesIndexGenerandoArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tags.
        /// </summary>
        public static string lblImagenesTags {
            get {
                return ResourceManager.GetString("lblImagenesTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios:.
        /// </summary>
        public static string lblImagenPreviewComentarios {
            get {
                return ResourceManager.GetString("lblImagenPreviewComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección:.
        /// </summary>
        public static string lblImagenPreviewDireccion {
            get {
                return ResourceManager.GetString("lblImagenPreviewDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Creación:.
        /// </summary>
        public static string lblImagenPreviewFechaCreacion {
            get {
                return ResourceManager.GetString("lblImagenPreviewFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto de Venta:.
        /// </summary>
        public static string lblImagenPreviewPuntoDeVenta {
            get {
                return ResourceManager.GetString("lblImagenPreviewPuntoDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte:.
        /// </summary>
        public static string lblImagenPreviewReporte {
            get {
                return ResourceManager.GetString("lblImagenPreviewReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags:.
        /// </summary>
        public static string lblImagenPreviewTags {
            get {
                return ResourceManager.GetString("lblImagenPreviewTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        public static string lblImagenPreviewUsuario {
            get {
                return ResourceManager.GetString("lblImagenPreviewUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar Filtros.
        /// </summary>
        public static string linkAplicarFiltro {
            get {
                return ResourceManager.GetString("linkAplicarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando mas imágenes.
        /// </summary>
        public static string loadingLabel {
            get {
                return ResourceManager.GetString("loadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron Fotos..
        /// </summary>
        public static string noFotosFound {
            get {
                return ResourceManager.GetString("noFotosFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte:.
        /// </summary>
        public static string reporteLabel {
            get {
                return ResourceManager.GetString("reporteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos.
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a la galería.
        /// </summary>
        public static string volverLabel {
            get {
                return ResourceManager.GetString("volverLabel", resourceCulture);
            }
        }
    }
}
