//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mapas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mapas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Mapas", typeof(Mapas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar Filtro.
        /// </summary>
        public static string btnMapasAplicarFiltroLabel {
            get {
                return ResourceManager.GetString("btnMapasAplicarFiltroLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre.
        /// </summary>
        public static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creacion.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Reporte.
        /// </summary>
        public static string fechaReporteLabel {
            get {
                return ResourceManager.GetString("fechaReporteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobertura.
        /// </summary>
        public static string layerCoberturaLabel {
            get {
                return ResourceManager.GetString("layerCoberturaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes por Usuario.
        /// </summary>
        public static string layerRepoUsuarioLabel {
            get {
                return ResourceManager.GetString("layerRepoUsuarioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimiento.
        /// </summary>
        public static string layerSeguimiento {
            get {
                return ResourceManager.GetString("layerSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string lblDetails {
            get {
                return ResourceManager.GetString("lblDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        public static string lblFilter {
            get {
                return ResourceManager.GetString("lblFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion:.
        /// </summary>
        public static string lblInfoPuntoDeVentaDireccion {
            get {
                return ResourceManager.GetString("lblInfoPuntoDeVentaDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Punto de Venta:.
        /// </summary>
        public static string lblInfoPuntoDeVentaIDPdv {
            get {
                return ResourceManager.GetString("lblInfoPuntoDeVentaIDPdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion:.
        /// </summary>
        public static string lblInfoReporteDireccion {
            get {
                return ResourceManager.GetString("lblInfoReporteDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Reporte:.
        /// </summary>
        public static string lblInfoReporteFechaReporte {
            get {
                return ResourceManager.GetString("lblInfoReporteFechaReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Reporte:.
        /// </summary>
        public static string lblInfoReporteIdReporting {
            get {
                return ResourceManager.GetString("lblInfoReporteIdReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string lblInfoReporteUsuario {
            get {
                return ResourceManager.GetString("lblInfoReporteUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimo reporte cargado.
        /// </summary>
        public static string lblLastReportCharged {
            get {
                return ResourceManager.GetString("lblLastReportCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando fotos....
        /// </summary>
        public static string lblLoadingPhotos {
            get {
                return ResourceManager.GetString("lblLoadingPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando Filtros....
        /// </summary>
        public static string lblMapasIndexCargandoFiltros {
            get {
                return ResourceManager.GetString("lblMapasIndexCargandoFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimiento Diario.
        /// </summary>
        public static string lblMapasIndexSeguimientoDiario {
            get {
                return ResourceManager.GetString("lblMapasIndexSeguimientoDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin reportes cargados.
        /// </summary>
        public static string lblNoReportsCharged {
            get {
                return ResourceManager.GetString("lblNoReportsCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Reporte.
        /// </summary>
        public static string lblReportID {
            get {
                return ResourceManager.GetString("lblReportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimiento Diario.
        /// </summary>
        public static string lblUserTracking {
            get {
                return ResourceManager.GetString("lblUserTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no tiene seguimiento para esta fecha.
        /// </summary>
        public static string lblUserTrackingNotData {
            get {
                return ResourceManager.GetString("lblUserTrackingNotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando mapa....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando....
        /// </summary>
        public static string loadingFilter {
            get {
                return ResourceManager.GetString("loadingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron fotos para el PDV.
        /// </summary>
        public static string NotExistsPhotos {
            get {
                return ResourceManager.GetString("NotExistsPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Firma.
        /// </summary>
        public static string NotSignature {
            get {
                return ResourceManager.GetString("NotSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta.
        /// </summary>
        public static string pdvLabel {
            get {
                return ResourceManager.GetString("pdvLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdv No Visitado.
        /// </summary>
        public static string pdvNoVisitado {
            get {
                return ResourceManager.GetString("pdvNoVisitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdv Visitado.
        /// </summary>
        public static string pdvVisitado {
            get {
                return ResourceManager.GetString("pdvVisitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        public static string PostalCodeAbbr {
            get {
                return ResourceManager.GetString("PostalCodeAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepción.
        /// </summary>
        public static string ReceptionDate {
            get {
                return ResourceManager.GetString("ReceptionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte.
        /// </summary>
        public static string reporteLabel {
            get {
                return ResourceManager.GetString("reporteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío.
        /// </summary>
        public static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se registran usuarios con ruta.
        /// </summary>
        public static string sinUsuariosConRuta {
            get {
                return ResourceManager.GetString("sinUsuariosConRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanencia en PDV.
        /// </summary>
        public static string TimeInPos {
            get {
                return ResourceManager.GetString("TimeInPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo.
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string totalLabel {
            get {
                return ResourceManager.GetString("totalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización.
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string usuarioLabel {
            get {
                return ResourceManager.GetString("usuarioLabel", resourceCulture);
            }
        }
    }
}
