//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PriceRequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PriceRequest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.PriceRequest", typeof(PriceRequest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string ActualState {
            get {
                return ResourceManager.GetString("ActualState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin PR.
        /// </summary>
        public static string AdminPriceRequest {
            get {
                return ResourceManager.GetString("AdminPriceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador Price Request.
        /// </summary>
        public static string AdminPriceRequest_ {
            get {
                return ResourceManager.GetString("AdminPriceRequest_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar.
        /// </summary>
        public static string ApproveRequest {
            get {
                return ResourceManager.GetString("ApproveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no puede estar vacío.
        /// </summary>
        public static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no puede ser cero.
        /// </summary>
        public static string CannotBeZero {
            get {
                return ResourceManager.GetString("CannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar estado.
        /// </summary>
        public static string ChangeState {
            get {
                return ResourceManager.GetString("ChangeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificando....
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string Commentary {
            get {
                return ResourceManager.GetString("Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competidores.
        /// </summary>
        public static string Competitors {
            get {
                return ResourceManager.GetString("Competitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea eliminar la solicitud?.
        /// </summary>
        public static string DeletePriceRequestConfirm {
            get {
                return ResourceManager.GetString("DeletePriceRequestConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string DeleteRequest {
            get {
                return ResourceManager.GetString("DeleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando....
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string DownloadRequest {
            get {
                return ResourceManager.GetString("DownloadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EditRequest {
            get {
                return ResourceManager.GetString("EditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOL.
        /// </summary>
        public static string EOL {
            get {
                return ResourceManager.GetString("EOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe seleccionar al menos un producto de la cuenta para la solicitud.
        /// </summary>
        public static string ErrorAtLeastOneProduct {
            get {
                return ResourceManager.GetString("ErrorAtLeastOneProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al aprobar solicitud.
        /// </summary>
        public static string ErrorOnAprroveRequest {
            get {
                return ResourceManager.GetString("ErrorOnAprroveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Delete Request.
        /// </summary>
        public static string ErrorOnDeleteRequest {
            get {
                return ResourceManager.GetString("ErrorOnDeleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en descarga.
        /// </summary>
        public static string ErrorOnDownload {
            get {
                return ResourceManager.GetString("ErrorOnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener fotos.
        /// </summary>
        public static string ErrorOnGetPhotos {
            get {
                return ResourceManager.GetString("ErrorOnGetPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar historial.
        /// </summary>
        public static string ErrorOnLoadHistory {
            get {
                return ResourceManager.GetString("ErrorOnLoadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo debe seleccionar un producto competidor.
        /// </summary>
        public static string ErrorOnlyOneCompetitor {
            get {
                return ResourceManager.GetString("ErrorOnlyOneCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al rechazar solicitud.
        /// </summary>
        public static string ErrorOnRejectPR {
            get {
                return ResourceManager.GetString("ErrorOnRejectPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un error al enviar solicitud.
        /// </summary>
        public static string ErrorOnSendPriceRequest {
            get {
                return ResourceManager.GetString("ErrorOnSendPriceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al validar solicitud.
        /// </summary>
        public static string ErrorOnValidateRequest {
            get {
                return ResourceManager.GetString("ErrorOnValidateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAP.
        /// </summary>
        public static string GAP {
            get {
                return ResourceManager.GetString("GAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar Detalles.
        /// </summary>
        public static string HideDetail {
            get {
                return ResourceManager.GetString("HideDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAP Ideal.
        /// </summary>
        public static string IdealGap {
            get {
                return ResourceManager.GetString("IdealGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Inicial.
        /// </summary>
        public static string InitialStatus {
            get {
                return ResourceManager.GetString("InitialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventario.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string LastState {
            get {
                return ResourceManager.GetString("LastState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Solicitudes de Baja de Precio.
        /// </summary>
        public static string ListPriceRequestTitle {
            get {
                return ResourceManager.GetString("ListPriceRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando historial....
        /// </summary>
        public static string LoadingHistory {
            get {
                return ResourceManager.GetString("LoadingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string ModificationDate {
            get {
                return ResourceManager.GetString("ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debe ser numérico.
        /// </summary>
        public static string MustBeNumeric {
            get {
                return ResourceManager.GetString("MustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetASP.
        /// </summary>
        public static string NetASP {
            get {
                return ResourceManager.GetString("NetASP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condicion NetASP .
        /// </summary>
        public static string NetASPCondition {
            get {
                return ResourceManager.GetString("NetASPCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variación % NetASP.
        /// </summary>
        public static string NetASPVariancePercent {
            get {
                return ResourceManager.GetString("NetASPVariancePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variación $ NetASP.
        /// </summary>
        public static string NetASPVariancePrice {
            get {
                return ResourceManager.GetString("NetASPVariancePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Gap.
        /// </summary>
        public static string NewGap {
            get {
                return ResourceManager.GetString("NewGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxima alerta en : .
        /// </summary>
        public static string NextAlertIn {
            get {
                return ResourceManager.GetString("NextAlertIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no se encontraron imagenes vinculadas al producto/cadena, mostrando fotos de los reportes.
        /// </summary>
        public static string NoPhotoForProduct {
            get {
                return ResourceManager.GetString("NoPhotoForProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen fotografias.
        /// </summary>
        public static string NoPhotoFound {
            get {
                return ResourceManager.GetString("NoPhotoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se Encontraron Solicitudes de Baja de Precio.
        /// </summary>
        public static string NoPriceRequestFound {
            get {
                return ResourceManager.GetString("NoPriceRequestFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor espere.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobado.
        /// </summary>
        public static string PR_Approved {
            get {
                return ResourceManager.GetString("PR_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargado.
        /// </summary>
        public static string PR_Downloaded {
            get {
                return ResourceManager.GetString("PR_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Descarga.
        /// </summary>
        public static string PR_DownloadError {
            get {
                return ResourceManager.GetString("PR_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Creada.
        /// </summary>
        public static string PR_Generated {
            get {
                return ResourceManager.GetString("PR_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Generación.
        /// </summary>
        public static string PR_InitialError {
            get {
                return ResourceManager.GetString("PR_InitialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Inicial.
        /// </summary>
        public static string PR_InitialStatus {
            get {
                return ResourceManager.GetString("PR_InitialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Estado.
        /// </summary>
        public static string PR_NoState {
            get {
                return ResourceManager.GetString("PR_NoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazada por EAI.
        /// </summary>
        public static string PR_RejectedByAdmin {
            get {
                return ResourceManager.GetString("PR_RejectedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazada por SEC.
        /// </summary>
        public static string PR_RejectedByManager {
            get {
                return ResourceManager.GetString("PR_RejectedByManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision OK.
        /// </summary>
        public static string PR_Revision {
            get {
                return ResourceManager.GetString("PR_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAP.
        /// </summary>
        public static string PriceGap {
            get {
                return ResourceManager.GetString("PriceGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Request.
        /// </summary>
        public static string PriceRequest_ {
            get {
                return ResourceManager.GetString("PriceRequest_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Request.
        /// </summary>
        public static string PriceRequestBTN {
            get {
                return ResourceManager.GetString("PriceRequestBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Request Closed.
        /// </summary>
        public static string PriceRequestClosed {
            get {
                return ResourceManager.GetString("PriceRequestClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario Baja de Precio.
        /// </summary>
        public static string PriceRequestForm {
            get {
                return ResourceManager.GetString("PriceRequestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variación de Precio.
        /// </summary>
        public static string PriceVariance {
            get {
                return ResourceManager.GetString("PriceVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        public static string RejectRequest {
            get {
                return ResourceManager.GetString("RejectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazo de solicitud (SEC).
        /// </summary>
        public static string RejectRequestSecTitle {
            get {
                return ResourceManager.GetString("RejectRequestSecTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese mensaje con motivo del rechazo.
        /// </summary>
        public static string RejectRequestSubtitle {
            get {
                return ResourceManager.GetString("RejectRequestSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar Solicitud de Baja de Precio.
        /// </summary>
        public static string RejectRequestTitle {
            get {
                return ResourceManager.GetString("RejectRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Aprobada.
        /// </summary>
        public static string RequestApproved {
            get {
                return ResourceManager.GetString("RequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Deleted.
        /// </summary>
        public static string RequestDeleted {
            get {
                return ResourceManager.GetString("RequestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario de Solicitud de Baja de Precio.
        /// </summary>
        public static string RequestFormTitle {
            get {
                return ResourceManager.GetString("RequestFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicutud Rechazada.
        /// </summary>
        public static string RequestRejected {
            get {
                return ResourceManager.GetString("RequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud enviada con éxíto.
        /// </summary>
        public static string RequestSendSuccesfull {
            get {
                return ResourceManager.GetString("RequestSendSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Enviada.
        /// </summary>
        public static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar en la Tabla.
        /// </summary>
        public static string SearchInTable {
            get {
                return ResourceManager.GetString("SearchInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos Seleccionadas.
        /// </summary>
        public static string SelectedPhotos {
            get {
                return ResourceManager.GetString("SelectedPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Foto.
        /// </summary>
        public static string SelectPhoto {
            get {
                return ResourceManager.GetString("SelectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione fotografias.
        /// </summary>
        public static string SelectPhotoFromGalery {
            get {
                return ResourceManager.GetString("SelectPhotoFromGalery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell In.
        /// </summary>
        public static string SellIn {
            get {
                return ResourceManager.GetString("SellIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Detalles.
        /// </summary>
        public static string ShowDetail {
            get {
                return ResourceManager.GetString("ShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiendas.
        /// </summary>
        public static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud aprobada con éxito.
        /// </summary>
        public static string SuccessOnApproveRequest {
            get {
                return ResourceManager.GetString("SuccessOnApproveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud rechazada con éxito.
        /// </summary>
        public static string SuccessOnRejectPR {
            get {
                return ResourceManager.GetString("SuccessOnRejectPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de baja de Precio.
        /// </summary>
        public static string TitlePriceRequest {
            get {
                return ResourceManager.GetString("TitlePriceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBP.
        /// </summary>
        public static string UBP {
            get {
                return ResourceManager.GetString("UBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propuesta UBP.
        /// </summary>
        public static string UBPProposal {
            get {
                return ResourceManager.GetString("UBPProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Modificada.
        /// </summary>
        public static string UpdatedStatus {
            get {
                return ResourceManager.GetString("UpdatedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar NetASP.
        /// </summary>
        public static string ValidateNetAsp {
            get {
                return ResourceManager.GetString("ValidateNetAsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar NetASP Condition.
        /// </summary>
        public static string ValidateNetAspCondition {
            get {
                return ResourceManager.GetString("ValidateNetAspCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetASP Condition no puede ser cero.
        /// </summary>
        public static string ValidateNetAspConditionZero {
            get {
                return ResourceManager.GetString("ValidateNetAspConditionZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar Propuesta UBP.
        /// </summary>
        public static string ValidateUbpProposal {
            get {
                return ResourceManager.GetString("ValidateUbpProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver PR.
        /// </summary>
        public static string ViewPriceRequest {
            get {
                return ResourceManager.GetString("ViewPriceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Solicitud.
        /// </summary>
        public static string ViewRequest {
            get {
                return ResourceManager.GetString("ViewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
