//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string lblCerrarSesion {
            get {
                return ResourceManager.GetString("lblCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpos Performance.
        /// </summary>
        public static string lblCheckposPerformance {
            get {
                return ResourceManager.GetString("lblCheckposPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde:.
        /// </summary>
        public static string lblDesde {
            get {
                return ResourceManager.GetString("lblDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa que estás viendo.
        /// </summary>
        public static string lblEmpresaQueEstasViendo {
            get {
                return ResourceManager.GetString("lblEmpresaQueEstasViendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404.
        /// </summary>
        public static string lblError404Titulo {
            get {
                return ResourceManager.GetString("lblError404Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops! 404..
        /// </summary>
        public static string lblError404Titulo2 {
            get {
                return ResourceManager.GetString("lblError404Titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permisos.
        /// </summary>
        public static string lblError501Titulo {
            get {
                return ResourceManager.GetString("lblError501Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esto no afectará sus datos..
        /// </summary>
        public static string lblErrorMensaje1 {
            get {
                return ResourceManager.GetString("lblErrorMensaje1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, contáctese con el.
        /// </summary>
        public static string lblErrorMensaje2 {
            get {
                return ResourceManager.GetString("lblErrorMensaje2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para que podamos ayudarle..
        /// </summary>
        public static string lblErrorMensaje3 {
            get {
                return ResourceManager.GetString("lblErrorMensaje3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops! Ocurrió un problema..
        /// </summary>
        public static string lblErrorTitulo {
            get {
                return ResourceManager.GetString("lblErrorTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros Aplicados.
        /// </summary>
        public static string lblFiltrosAplicadosLabel {
            get {
                return ResourceManager.GetString("lblFiltrosAplicadosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta:.
        /// </summary>
        public static string lblHasta {
            get {
                return ResourceManager.GetString("lblHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string lblLayoutMisDatosDePerfil {
            get {
                return ResourceManager.GetString("lblLayoutMisDatosDePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertas.
        /// </summary>
        public static string lblLinkAlertas {
            get {
                return ResourceManager.GetString("lblLinkAlertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendario.
        /// </summary>
        public static string lblLinkCalendario {
            get {
                return ResourceManager.GetString("lblLinkCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta cuenta se ha bloqueado, inténtelo de nuevo más tarde..
        /// </summary>
        public static string lblLockoutMensaje {
            get {
                return ResourceManager.GetString("lblLockoutMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        public static string lblLockoutTitulo {
            get {
                return ResourceManager.GetString("lblLockoutTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado..
        /// </summary>
        public static string lblLockoutTitulo2 {
            get {
                return ResourceManager.GetString("lblLockoutTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron datos.
        /// </summary>
        public static string lblNoDataFoundTitulo {
            get {
                return ResourceManager.GetString("lblNoDataFoundTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene Cliente.
        /// </summary>
        public static string lblNoTieneCliente {
            get {
                return ResourceManager.GetString("lblNoTieneCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene Filtros.
        /// </summary>
        public static string lblNoTieneFiltrosTitulo {
            get {
                return ResourceManager.GetString("lblNoTieneFiltrosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soporte CheckPOS.
        /// </summary>
        public static string lblSoporteCheckPOS {
            get {
                return ResourceManager.GetString("lblSoporteCheckPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no presenta ningún cliente asociado..
        /// </summary>
        public static string lblUsuarioSinClienteMensaje1 {
            get {
                return ResourceManager.GetString("lblUsuarioSinClienteMensaje1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede continuar.
        /// </summary>
        public static string lblUsuarioSinClienteMensaje2 {
            get {
                return ResourceManager.GetString("lblUsuarioSinClienteMensaje2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente no asociado.
        /// </summary>
        public static string lblUsuarioSinClienteSeleccionadoTitulo {
            get {
                return ResourceManager.GetString("lblUsuarioSinClienteSeleccionadoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
    }
}
