//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tableros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tableros() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reporting.Resources.Tableros", typeof(Tableros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar un tablero a esta lista.
        /// </summary>
        public static string admAgregarTablero {
            get {
                return ResourceManager.GetString("admAgregarTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar Objetos.
        /// </summary>
        public static string admConfigurarObjetos {
            get {
                return ResourceManager.GetString("admConfigurarObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string admLabelEditar {
            get {
                return ResourceManager.GetString("admLabelEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string admLabelEliminar {
            get {
                return ResourceManager.GetString("admLabelEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos.
        /// </summary>
        public static string admLabelPermisos {
            get {
                return ResourceManager.GetString("admLabelPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string admLabelVer {
            get {
                return ResourceManager.GetString("admLabelVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No, dejalo ahí..
        /// </summary>
        public static string admNoEliminar {
            get {
                return ResourceManager.GetString("admNoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar permanentemente este tablero?.
        /// </summary>
        public static string admPreguntaEliminar {
            get {
                return ResourceManager.GetString("admPreguntaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si, eliminalo.
        /// </summary>
        public static string admSiEliminar {
            get {
                return ResourceManager.GetString("admSiEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar Tableros.
        /// </summary>
        public static string admTitulo {
            get {
                return ResourceManager.GetString("admTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ampliar.
        /// </summary>
        public static string ampliar {
            get {
                return ResourceManager.GetString("ampliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No posee ningún cliente asignado.
        /// </summary>
        public static string clientenoasignado {
            get {
                return ResourceManager.GetString("clientenoasignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string clientesModalCerrar {
            get {
                return ResourceManager.GetString("clientesModalCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string clientesModalGuardar {
            get {
                return ResourceManager.GetString("clientesModalGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente Seleccionado.
        /// </summary>
        public static string clientesModalTitle {
            get {
                return ResourceManager.GetString("clientesModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo completar la operación.
        /// </summary>
        public static string confFiltroErrorSetearCheck {
            get {
                return ResourceManager.GetString("confFiltroErrorSetearCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo setear el nombre del filtro.
        /// </summary>
        public static string confFiltroErrorSetearNombre {
            get {
                return ResourceManager.GetString("confFiltroErrorSetearNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo resetear el nombre del filtro.
        /// </summary>
        public static string confFiltroResetError {
            get {
                return ResourceManager.GetString("confFiltroResetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron filtros.
        /// </summary>
        public static string confFiltroSinFiltros {
            get {
                return ResourceManager.GetString("confFiltroSinFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar Gráfico.
        /// </summary>
        public static string configurarGrafico {
            get {
                return ResourceManager.GetString("configurarGrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo setear el nombre del objeto.
        /// </summary>
        public static string confObjetoErrorSetearNombre {
            get {
                return ResourceManager.GetString("confObjetoErrorSetearNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo resetear el nombre del objeto.
        /// </summary>
        public static string confObjetoResetError {
            get {
                return ResourceManager.GetString("confObjetoResetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nuevo usuario.
        /// </summary>
        public static string crearNuevoUsuarioModalTitulo {
            get {
                return ResourceManager.GetString("crearNuevoUsuarioModalTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Objetos al Tablero.
        /// </summary>
        public static string crearTableroBtnAgregarObjetos {
            get {
                return ResourceManager.GetString("crearTableroBtnAgregarObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        public static string crearTableroBtnEliminar {
            get {
                return ResourceManager.GetString("crearTableroBtnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Tablero.
        /// </summary>
        public static string crearTableroBtnSave {
            get {
                return ResourceManager.GetString("crearTableroBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string crearTableroColNombre {
            get {
                return ResourceManager.GetString("crearTableroColNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        public static string crearTableroColOrden {
            get {
                return ResourceManager.GetString("crearTableroColOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        public static string crearTableroColSize {
            get {
                return ResourceManager.GetString("crearTableroColSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string crearTableroColTipo {
            get {
                return ResourceManager.GetString("crearTableroColTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre los items para cambiar la posición que tendrán dentro del tablero..
        /// </summary>
        public static string crearTableroDragDropOrderLabel {
            get {
                return ResourceManager.GetString("crearTableroDragDropOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si, eliminalo.
        /// </summary>
        public static string crearTableroEliminarAceptar {
            get {
                return ResourceManager.GetString("crearTableroEliminarAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No, dejalo ahí..
        /// </summary>
        public static string crearTableroEliminarCancelar {
            get {
                return ResourceManager.GetString("crearTableroEliminarCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar permanentemente este gráfico?.
        /// </summary>
        public static string crearTableroEliminarPregunta {
            get {
                return ResourceManager.GetString("crearTableroEliminarPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe asignarle un nombre al tablero.
        /// </summary>
        public static string crearTableroErrNombreVacio {
            get {
                return ResourceManager.GetString("crearTableroErrNombreVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Seleccionar al menos un Gráfico.
        /// </summary>
        public static string crearTableroErrNoObjectSelected {
            get {
                return ResourceManager.GetString("crearTableroErrNoObjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos disponibles.
        /// </summary>
        public static string crearTableroLabelObjDisponibles {
            get {
                return ResourceManager.GetString("crearTableroLabelObjDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos seleccionados.
        /// </summary>
        public static string crearTableroLabelObjSeleccionados {
            get {
                return ResourceManager.GetString("crearTableroLabelObjSeleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string crearTablerolblNombre {
            get {
                return ResourceManager.GetString("crearTablerolblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona los gráficos que quieras ver en este tablero.
        /// </summary>
        public static string crearTableroSelObjetosLabel {
            get {
                return ResourceManager.GetString("crearTableroSelObjetosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aún no has seleccionado gráficos para este tablero..
        /// </summary>
        public static string crearTableroSinObjetos {
            get {
                return ResourceManager.GetString("crearTableroSinObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Nuevo Tablero.
        /// </summary>
        public static string crearTableroTitulo {
            get {
                return ResourceManager.GetString("crearTableroTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Tablero.
        /// </summary>
        public static string crearTableroTituloPanel {
            get {
                return ResourceManager.GetString("crearTableroTituloPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver sin guardar.
        /// </summary>
        public static string crearTableroVolverLabel {
            get {
                return ResourceManager.GetString("crearTableroVolverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Datos.
        /// </summary>
        public static string descargarDatos {
            get {
                return ResourceManager.GetString("descargarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Imagen.
        /// </summary>
        public static string descargarImagen {
            get {
                return ResourceManager.GetString("descargarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Objetos al Tablero.
        /// </summary>
        public static string editarTableroBtnAgregarObjetos {
            get {
                return ResourceManager.GetString("editarTableroBtnAgregarObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        public static string editarTableroBtnEliminar {
            get {
                return ResourceManager.GetString("editarTableroBtnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string editarTableroBtnSave {
            get {
                return ResourceManager.GetString("editarTableroBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string editarTableroColNombre {
            get {
                return ResourceManager.GetString("editarTableroColNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        public static string editarTableroColOrden {
            get {
                return ResourceManager.GetString("editarTableroColOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        public static string editarTableroColSize {
            get {
                return ResourceManager.GetString("editarTableroColSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string editarTableroColTipo {
            get {
                return ResourceManager.GetString("editarTableroColTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre los items para cambiar la posición que tendrán dentro del tablero..
        /// </summary>
        public static string editarTableroDragDropOrderLabel {
            get {
                return ResourceManager.GetString("editarTableroDragDropOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si, eliminalo.
        /// </summary>
        public static string editarTableroEliminarAceptar {
            get {
                return ResourceManager.GetString("editarTableroEliminarAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No, dejalo ahí..
        /// </summary>
        public static string editarTableroEliminarCancelar {
            get {
                return ResourceManager.GetString("editarTableroEliminarCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar permanentemente este gráfico?.
        /// </summary>
        public static string editarTableroEliminarPregunta {
            get {
                return ResourceManager.GetString("editarTableroEliminarPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe asignarle un nombre al tablero.
        /// </summary>
        public static string editarTableroErrNombreVacio {
            get {
                return ResourceManager.GetString("editarTableroErrNombreVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Seleccionar al menos un Gráfico.
        /// </summary>
        public static string editarTableroErrNoObjectSelected {
            get {
                return ResourceManager.GetString("editarTableroErrNoObjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos disponibles.
        /// </summary>
        public static string editarTableroLabelObjDisponibles {
            get {
                return ResourceManager.GetString("editarTableroLabelObjDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos seleccionados.
        /// </summary>
        public static string editarTableroLabelObjSeleccionados {
            get {
                return ResourceManager.GetString("editarTableroLabelObjSeleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string editarTablerolblNombre {
            get {
                return ResourceManager.GetString("editarTablerolblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona los gráficos que quieras ver en este tablero.
        /// </summary>
        public static string editarTableroSelObjetosLabel {
            get {
                return ResourceManager.GetString("editarTableroSelObjetosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aún no has seleccionado gráficos para este tablero..
        /// </summary>
        public static string editarTableroSinObjetos {
            get {
                return ResourceManager.GetString("editarTableroSinObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Tablero.
        /// </summary>
        public static string editarTableroTitulo {
            get {
                return ResourceManager.GetString("editarTableroTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Tablero.
        /// </summary>
        public static string editarTableroTituloPanel {
            get {
                return ResourceManager.GetString("editarTableroTituloPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver sin guardar.
        /// </summary>
        public static string editarTableroVolverLabel {
            get {
                return ResourceManager.GetString("editarTableroVolverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Contraseña ingresada es incorrecta.
        /// </summary>
        public static string errClaveIncorrecta {
            get {
                return ResourceManager.GetString("errClaveIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No pudo eliminarse el tablero.
        /// </summary>
        public static string errEliminarTablero {
            get {
                return ResourceManager.GetString("errEliminarTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los formatos de imagen soportados son gif, jpg, png.
        /// </summary>
        public static string errFormatosImagen {
            get {
                return ResourceManager.GetString("errFormatosImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al grabar permisos.
        /// </summary>
        public static string errGrabarPermisos {
            get {
                return ResourceManager.GetString("errGrabarPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar guardarlos datos de usuario..
        /// </summary>
        public static string errGuardarDatosUsuario {
            get {
                return ResourceManager.GetString("errGuardarDatosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a error guardar nuevo tipo de objeto - Ampliar.
        /// </summary>
        public static string errGuardarTipoObjetoAmpliar {
            get {
                return ResourceManager.GetString("errGuardarTipoObjetoAmpliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La extensión del archivo seleccionado no está permitida.
        /// </summary>
        public static string errImagenFormatoInvalido {
            get {
                return ResourceManager.GetString("errImagenFormatoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen no puede superarlos 500kb.
        /// </summary>
        public static string errImagenSize500kb {
            get {
                return ResourceManager.GetString("errImagenSize500kb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion no soportada para chart type distinto de 9.
        /// </summary>
        public static string errOperacionNoSoportadaTipo9 {
            get {
                return ResourceManager.GetString("errOperacionNoSoportadaTipo9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Para visualizar los cambios debe actualizar el tablero).
        /// </summary>
        public static string lblActualiceParaVisualizar {
            get {
                return ResourceManager.GetString("lblActualiceParaVisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar Filtro.
        /// </summary>
        public static string lblAplicarFiltro {
            get {
                return ResourceManager.GetString("lblAplicarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string lblCambiarContraseña {
            get {
                return ResourceManager.GetString("lblCambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string lblCancelar {
            get {
                return ResourceManager.GetString("lblCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando Filtros....
        /// </summary>
        public static string lblCargandoFiltros {
            get {
                return ResourceManager.GetString("lblCargandoFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando Tablero....
        /// </summary>
        public static string lblCargandoTablero {
            get {
                return ResourceManager.GetString("lblCargandoTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string lblCerrar {
            get {
                return ResourceManager.GetString("lblCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escritura.
        /// </summary>
        public static string lblColEscritura {
            get {
                return ResourceManager.GetString("lblColEscritura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lectura.
        /// </summary>
        public static string lblColLectura {
            get {
                return ResourceManager.GetString("lblColLectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string lblColNombre {
            get {
                return ResourceManager.GetString("lblColNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string lblColUsuario {
            get {
                return ResourceManager.GetString("lblColUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardando cambios....
        /// </summary>
        public static string lblGuardandoCambios {
            get {
                return ResourceManager.GetString("lblGuardandoCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string lblGuardarCambios {
            get {
                return ResourceManager.GetString("lblGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos de usuario se guardaron exitosamente.
        /// </summary>
        public static string lblLosDatosSeGuardaronExito {
            get {
                return ResourceManager.GetString("lblLosDatosSeGuardaronExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis datos de perfil.
        /// </summary>
        public static string lblMisDatosTitulo {
            get {
                return ResourceManager.GetString("lblMisDatosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene Objetos.
        /// </summary>
        public static string lblNoPoseeObjetosTitulo {
            get {
                return ResourceManager.GetString("lblNoPoseeObjetosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar.
        /// </summary>
        public static string lblPermisosAsignar {
            get {
                return ResourceManager.GetString("lblPermisosAsignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos.
        /// </summary>
        public static string lblPermisosTitulo {
            get {
                return ResourceManager.GetString("lblPermisosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persistir cambio de objeto en el tablero.
        /// </summary>
        public static string lblPersistirCambiosEnTablero {
            get {
                return ResourceManager.GetString("lblPersistirCambiosEnTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecccionar Objetos.
        /// </summary>
        public static string lblSeleccionarObjetos {
            get {
                return ResourceManager.GetString("lblSeleccionarObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un Rol.
        /// </summary>
        public static string lblSeleccioneUnRol {
            get {
                return ResourceManager.GetString("lblSeleccioneUnRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede modificar sus datos de perfil asi como el idioma en que visualiza el sitio.
        /// </summary>
        public static string lblSubTituloDatosPerfil {
            get {
                return ResourceManager.GetString("lblSubTituloDatosPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Datos de Perfil.
        /// </summary>
        public static string lblTituloMisDatosPerfil {
            get {
                return ResourceManager.GetString("lblTituloMisDatosPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Tablero.
        /// </summary>
        public static string lblTituloNoTienePermisosTableros {
            get {
                return ResourceManager.GetString("lblTituloNoTienePermisosTableros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene Tableros.
        /// </summary>
        public static string lblTituloNoTieneTableros {
            get {
                return ResourceManager.GetString("lblTituloNoTieneTableros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todo/Ninguno.
        /// </summary>
        public static string lblTodoNinguno {
            get {
                return ResourceManager.GetString("lblTodoNinguno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string lblYesNoNo {
            get {
                return ResourceManager.GetString("lblYesNoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string lblYesNoYes {
            get {
                return ResourceManager.GetString("lblYesNoYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abms.
        /// </summary>
        public static string linkAbms {
            get {
                return ResourceManager.GetString("linkAbms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar mis tableros.
        /// </summary>
        public static string linkAdministrarTablero {
            get {
                return ResourceManager.GetString("linkAdministrarTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string linkConfiguracion {
            get {
                return ResourceManager.GetString("linkConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        public static string linkConfigurarFiltros {
            get {
                return ResourceManager.GetString("linkConfigurarFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Nuevo Tablero.
        /// </summary>
        public static string linkCrearTablero {
            get {
                return ResourceManager.GetString("linkCrearTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos.
        /// </summary>
        public static string linkDatos {
            get {
                return ResourceManager.GetString("linkDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Tablero Actual.
        /// </summary>
        public static string linkEditarTablero {
            get {
                return ResourceManager.GetString("linkEditarTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imágenes.
        /// </summary>
        public static string linkImagenes {
            get {
                return ResourceManager.GetString("linkImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapas.
        /// </summary>
        public static string linkMaps {
            get {
                return ResourceManager.GetString("linkMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres de Objetos.
        /// </summary>
        public static string linkNombreObjetos {
            get {
                return ResourceManager.GetString("linkNombreObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tableros.
        /// </summary>
        public static string linkTableros {
            get {
                return ResourceManager.GetString("linkTableros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string menuClientesLabel {
            get {
                return ResourceManager.GetString("menuClientesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string menuPerfilLabel {
            get {
                return ResourceManager.GetString("menuPerfilLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string menuSalirLabel {
            get {
                return ResourceManager.GetString("menuSalirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró información.
        /// </summary>
        public static string noDataFoundGrafico {
            get {
                return ResourceManager.GetString("noDataFoundGrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene un cliente asignado.
        /// </summary>
        public static string notienecliente {
            get {
                return ResourceManager.GetString("notienecliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un cliente para acceder a esta pantalla.
        /// </summary>
        public static string notieneclientesubtitulo {
            get {
                return ResourceManager.GetString("notieneclientesubtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene filtros asignados.
        /// </summary>
        public static string noTieneFiltros {
            get {
                return ResourceManager.GetString("noTieneFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe tener al menos 1 filtro asignado para accedeer a esta pantalla.
        /// </summary>
        public static string noTieneFiltrosSubTitulo {
            get {
                return ResourceManager.GetString("noTieneFiltrosSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene objetos asignados.
        /// </summary>
        public static string noTieneObjetos {
            get {
                return ResourceManager.GetString("noTieneObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesita tener al menos un objeto asignado para acceder a esta pantalla.
        /// </summary>
        public static string noTieneObjetosSubTitulo {
            get {
                return ResourceManager.GetString("noTieneObjetosSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene permisos.
        /// </summary>
        public static string notienepermisos {
            get {
                return ResourceManager.GetString("notienepermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está autorizado a ingresar en esta sección.
        /// </summary>
        public static string notienepermisossubtitulo {
            get {
                return ResourceManager.GetString("notienepermisossubtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tablero compartido es de solo lectura, no puede editarlo.
        /// </summary>
        public static string notienePermisostablerosSubTitulo {
            get {
                return ResourceManager.GetString("notienePermisostablerosSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: No tiene pemisos de edición.
        /// </summary>
        public static string notienePermisostablerosTitulo {
            get {
                return ResourceManager.GetString("notienePermisostablerosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Crea uno ahora!.
        /// </summary>
        public static string notienetablerosSubTitulo {
            get {
                return ResourceManager.GetString("notienetablerosSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aún no has creado ningún tablero..
        /// </summary>
        public static string notienetablerosTitulo {
            get {
                return ResourceManager.GetString("notienetablerosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron usuarios.
        /// </summary>
        public static string noTieneUsuarios {
            get {
                return ResourceManager.GetString("noTieneUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede visualizar el listado de usuarios.
        /// </summary>
        public static string noTieneUsuariosSubTitulo {
            get {
                return ResourceManager.GetString("noTieneUsuariosSubTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño de la imagen no puede exceder 100kb.
        /// </summary>
        public static string perfil_imageSizeWarning {
            get {
                return ResourceManager.GetString("perfil_imageSizeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar una contraseña.
        /// </summary>
        public static string perfil_lblClaveActualVacia {
            get {
                return ResourceManager.GetString("perfil_lblClaveActualVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nueva contraseña debe tener al menos 6 caracteres.
        /// </summary>
        public static string perfil_lblClaveDebil {
            get {
                return ResourceManager.GetString("perfil_lblClaveDebil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar una nueva contraseña.
        /// </summary>
        public static string perfil_lblClaveNuevaVacia {
            get {
                return ResourceManager.GetString("perfil_lblClaveNuevaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas deben coincidir.
        /// </summary>
        public static string perfil_lblClavesNoCoinciden {
            get {
                return ResourceManager.GetString("perfil_lblClavesNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Actual.
        /// </summary>
        public static string perfilClaveActual {
            get {
                return ResourceManager.GetString("perfilClaveActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe escribir su contraseña actual.
        /// </summary>
        public static string perfilClaveActualContent {
            get {
                return ResourceManager.GetString("perfilClaveActualContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Actual.
        /// </summary>
        public static string perfilClaveActualPlaceHolder {
            get {
                return ResourceManager.GetString("perfilClaveActualPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string perfilClaveLabel {
            get {
                return ResourceManager.GetString("perfilClaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        public static string perfilClaveNueva {
            get {
                return ResourceManager.GetString("perfilClaveNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe cofirmar la nueva contraseña.
        /// </summary>
        public static string perfilClaveNuevaConfirmarContent {
            get {
                return ResourceManager.GetString("perfilClaveNuevaConfirmarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme su nueva contraseña.
        /// </summary>
        public static string perfilClaveNuevaConfirmarPlaceholder {
            get {
                return ResourceManager.GetString("perfilClaveNuevaConfirmarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe escribir una contraseña nueva.
        /// </summary>
        public static string perfilClaveNuevaContent {
            get {
                return ResourceManager.GetString("perfilClaveNuevaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string perfilClaveNuevaPlaceHolder {
            get {
                return ResourceManager.GetString("perfilClaveNuevaPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme su nueva contraseña.
        /// </summary>
        public static string perfilConfirmeClaveText {
            get {
                return ResourceManager.GetString("perfilConfirmeClaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string perfilModalCerrar {
            get {
                return ResourceManager.GetString("perfilModalCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string perfilModalGuardar {
            get {
                return ResourceManager.GetString("perfilModalGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de Perfil.
        /// </summary>
        public static string perfilModalTitulo {
            get {
                return ResourceManager.GetString("perfilModalTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar Usuarios....
        /// </summary>
        public static string placeholderFiltrarUsuarios {
            get {
                return ResourceManager.GetString("placeholderFiltrarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor revise si los datos son correctos.
        /// </summary>
        public static string reviseSiLosResultadosSonCorrectos {
            get {
                return ResourceManager.GetString("reviseSiLosResultadosSonCorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tableros.
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
    }
}
