// <auto-generated />
namespace Reporting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class qwerty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qwerty));
        
        string IMigrationMetadata.Id
        {
            get { return "201511260045462_qwerty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
